-- ============================================================================
-- FILE: 02_item_master.sql
-- DESCRIPTION: Item Master, Variants, Attributes, UOM, Lot/Serial, Org Assignment
-- ============================================================================

-- ==========================================================================
-- SEQUENCES
-- ==========================================================================
CREATE SEQUENCE SEQ_CATEGORY_ID         START WITH 1000001 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ITEM_ID             START WITH 1000001 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ATTRIBUTE_ID        START WITH 1000001 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ATTRIBUTE_VALUE_ID  START WITH 1000001 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_VARIANT_ID          START WITH 1000001 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_VAV_ID              START WITH 1000001 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ITEM_ORG_ASSIGN_ID  START WITH 1000001 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_LOT_SERIAL_ID       START WITH 1000001 INCREMENT BY 1 NOCACHE NOCYCLE;

-- ==========================================================================
-- TABLE 1: POS_UNITS_OF_MEASURE
-- ==========================================================================
CREATE TABLE POS_UNITS_OF_MEASURE (
    UOM_CODE                VARCHAR2(20)    NOT NULL,
    UOM_NAME_EN             VARCHAR2(100)   NOT NULL,
    UOM_NAME_AR             VARCHAR2(100),
    UOM_CLASS               VARCHAR2(30)    NOT NULL,
    BASE_UOM_CODE           VARCHAR2(20),
    CONVERSION_RATE         NUMBER(18,10)   DEFAULT 1 NOT NULL,
    DECIMAL_PLACES          NUMBER(2)       DEFAULT 2,
    IS_ACTIVE               CHAR(1)         DEFAULT 'Y' NOT NULL,
    CONSTRAINT POS_UOM_PK       PRIMARY KEY (UOM_CODE),
    CONSTRAINT POS_UOM_BASE_FK  FOREIGN KEY (BASE_UOM_CODE) REFERENCES POS_UNITS_OF_MEASURE(UOM_CODE),
    CONSTRAINT POS_UOM_CLASS_CHK CHECK (UOM_CLASS IN ('QUANTITY','WEIGHT','VOLUME','TIME','LENGTH','AREA')),
    CONSTRAINT POS_UOM_ACTIVE_CHK CHECK (IS_ACTIVE IN ('Y','N'))
);

COMMENT ON TABLE POS_UNITS_OF_MEASURE IS 'Unit of Measure master with UOM class and inter-UOM conversion rates.';
COMMENT ON COLUMN POS_UNITS_OF_MEASURE.BASE_UOM_CODE IS 'Base UOM within its class. Conversion rate is relative to this base.';
COMMENT ON COLUMN POS_UNITS_OF_MEASURE.CONVERSION_RATE IS 'How many base UOM units equal 1 of this UOM. e.g., 1 KG = 1000 G so GRAM.CONVERSION_RATE=0.001.';

-- Seed common UOMs
INSERT INTO POS_UNITS_OF_MEASURE(UOM_CODE,UOM_NAME_EN,UOM_NAME_AR,UOM_CLASS,BASE_UOM_CODE,CONVERSION_RATE) VALUES('EA','Each','قطعة','QUANTITY',NULL,1);
INSERT INTO POS_UNITS_OF_MEASURE(UOM_CODE,UOM_NAME_EN,UOM_NAME_AR,UOM_CLASS,BASE_UOM_CODE,CONVERSION_RATE) VALUES('DZ','Dozen','دزينة','QUANTITY','EA',12);
INSERT INTO POS_UNITS_OF_MEASURE(UOM_CODE,UOM_NAME_EN,UOM_NAME_AR,UOM_CLASS,BASE_UOM_CODE,CONVERSION_RATE) VALUES('KG','Kilogram','كيلوجرام','WEIGHT',NULL,1);
INSERT INTO POS_UNITS_OF_MEASURE(UOM_CODE,UOM_NAME_EN,UOM_NAME_AR,UOM_CLASS,BASE_UOM_CODE,CONVERSION_RATE) VALUES('G','Gram','جرام','WEIGHT','KG',0.001);
INSERT INTO POS_UNITS_OF_MEASURE(UOM_CODE,UOM_NAME_EN,UOM_NAME_AR,UOM_CLASS,BASE_UOM_CODE,CONVERSION_RATE) VALUES('LTR','Liter','لتر','VOLUME',NULL,1);
INSERT INTO POS_UNITS_OF_MEASURE(UOM_CODE,UOM_NAME_EN,UOM_NAME_AR,UOM_CLASS,BASE_UOM_CODE,CONVERSION_RATE) VALUES('ML','Milliliter','مليلتر','VOLUME','LTR',0.001);
INSERT INTO POS_UNITS_OF_MEASURE(UOM_CODE,UOM_NAME_EN,UOM_NAME_AR,UOM_CLASS,BASE_UOM_CODE,CONVERSION_RATE) VALUES('HR','Hour','ساعة','TIME',NULL,1);
INSERT INTO POS_UNITS_OF_MEASURE(UOM_CODE,UOM_NAME_EN,UOM_NAME_AR,UOM_CLASS,BASE_UOM_CODE,CONVERSION_RATE) VALUES('MIN','Minute','دقيقة','TIME','HR',0.0166667);
COMMIT;

-- ==========================================================================
-- TABLE 2: POS_ITEM_CATEGORIES
-- ==========================================================================
CREATE TABLE POS_ITEM_CATEGORIES (
    CATEGORY_ID             NUMBER          DEFAULT SEQ_CATEGORY_ID.NEXTVAL NOT NULL,
    CATEGORY_CODE           VARCHAR2(50)    NOT NULL,
    CATEGORY_NAME_EN        VARCHAR2(240)   NOT NULL,
    CATEGORY_NAME_AR        VARCHAR2(240),
    PARENT_CATEGORY_ID      NUMBER,
    CATEGORY_LEVEL          NUMBER(2)       DEFAULT 1,
    TAX_CATEGORY_CODE       VARCHAR2(30),
    IMAGE_URL               VARCHAR2(500),
    COLOR_HEX               VARCHAR2(7),
    ICON_CLASS              VARCHAR2(100),
    SORT_ORDER              NUMBER          DEFAULT 10,
    IS_ACTIVE               CHAR(1)         DEFAULT 'Y' NOT NULL,
    CREATED_BY              NUMBER,
    CREATION_DATE           DATE            DEFAULT SYSDATE,
    LAST_UPDATED_BY         NUMBER,
    LAST_UPDATE_DATE        DATE,
    CONSTRAINT POS_IC_PK        PRIMARY KEY (CATEGORY_ID),
    CONSTRAINT POS_IC_CODE_UK   UNIQUE (CATEGORY_CODE),
    CONSTRAINT POS_IC_PARENT_FK FOREIGN KEY (PARENT_CATEGORY_ID) REFERENCES POS_ITEM_CATEGORIES(CATEGORY_ID),
    CONSTRAINT POS_IC_ACTIVE_CHK CHECK (IS_ACTIVE IN ('Y','N'))
);

COMMENT ON TABLE POS_ITEM_CATEGORIES IS 'Hierarchical item categories. Supports multi-level category trees via self-referencing PARENT_CATEGORY_ID.';
COMMENT ON COLUMN POS_ITEM_CATEGORIES.TAX_CATEGORY_CODE IS 'Links to POS_TAX_RULES for category-level tax determination.';
COMMENT ON COLUMN POS_ITEM_CATEGORIES.COLOR_HEX IS 'Hex color code for POS UI category button (e.g. #FF5722).';

CREATE INDEX POS_IC_PARENT_IDX ON POS_ITEM_CATEGORIES(PARENT_CATEGORY_ID);
CREATE INDEX POS_IC_ACTIVE_IDX ON POS_ITEM_CATEGORIES(IS_ACTIVE);

-- ==========================================================================
-- TABLE 3: POS_ITEMS
-- ==========================================================================
CREATE TABLE POS_ITEMS (
    ITEM_ID                 NUMBER          DEFAULT SEQ_ITEM_ID.NEXTVAL NOT NULL,
    ITEM_CODE               VARCHAR2(50)    NOT NULL,
    ITEM_NAME_EN            VARCHAR2(240)   NOT NULL,
    ITEM_NAME_AR            VARCHAR2(240),
    CATEGORY_ID             NUMBER          NOT NULL,
    ITEM_TYPE               VARCHAR2(20)    DEFAULT 'PRODUCT' NOT NULL,
    SECTOR_TYPE             VARCHAR2(20)    DEFAULT 'ALL' NOT NULL,
    PRIMARY_UOM_CODE        VARCHAR2(20)    NOT NULL,
    SECONDARY_UOM_CODE      VARCHAR2(20),
    BARCODE                 VARCHAR2(100),
    ALT_BARCODE             VARCHAR2(100),
    DESCRIPTION_EN          CLOB,
    DESCRIPTION_AR          CLOB,
    IMAGE_URL               VARCHAR2(500),
    IMAGE_THUMBNAIL_URL     VARCHAR2(500),
    HAS_VARIANTS            CHAR(1)         DEFAULT 'N' NOT NULL,
    HAS_SERIAL              CHAR(1)         DEFAULT 'N' NOT NULL,
    HAS_LOT                 CHAR(1)         DEFAULT 'N' NOT NULL,
    IS_EXPIRY_TRACKED       CHAR(1)         DEFAULT 'N' NOT NULL,
    IS_WEIGHABLE            CHAR(1)         DEFAULT 'N' NOT NULL,
    IS_OPEN_PRICE           CHAR(1)         DEFAULT 'N' NOT NULL,
    IS_TAXABLE              CHAR(1)         DEFAULT 'Y' NOT NULL,
    TAX_CATEGORY_CODE       VARCHAR2(30),
    COST_PRICE              NUMBER(18,6),
    MIN_SALE_PRICE          NUMBER(18,6),
    KDS_CATEGORY            VARCHAR2(50),
    PREP_TIME_MINUTES       NUMBER,
    SORT_ORDER              NUMBER          DEFAULT 10,
    IS_ACTIVE               CHAR(1)         DEFAULT 'Y' NOT NULL,
    CREATED_BY              NUMBER,
    CREATION_DATE           DATE            DEFAULT SYSDATE,
    LAST_UPDATED_BY         NUMBER,
    LAST_UPDATE_DATE        DATE,
    CONSTRAINT POS_IT_PK        PRIMARY KEY (ITEM_ID),
    CONSTRAINT POS_IT_CODE_UK   UNIQUE (ITEM_CODE),
    CONSTRAINT POS_IT_CAT_FK    FOREIGN KEY (CATEGORY_ID) REFERENCES POS_ITEM_CATEGORIES(CATEGORY_ID),
    CONSTRAINT POS_IT_UOM_FK    FOREIGN KEY (PRIMARY_UOM_CODE) REFERENCES POS_UNITS_OF_MEASURE(UOM_CODE),
    CONSTRAINT POS_IT_UOM2_FK   FOREIGN KEY (SECONDARY_UOM_CODE) REFERENCES POS_UNITS_OF_MEASURE(UOM_CODE),
    CONSTRAINT POS_IT_TYPE_CHK  CHECK (ITEM_TYPE IN ('PRODUCT','SERVICE','BUNDLE','COMPONENT','MODIFIER')),
    CONSTRAINT POS_IT_SECTOR_CHK CHECK (SECTOR_TYPE IN ('RETAIL','FNB','SERVICE','ALL')),
    CONSTRAINT POS_IT_ACTIVE_CHK CHECK (IS_ACTIVE IN ('Y','N'))
);

COMMENT ON TABLE POS_ITEMS IS 'Item Master at the style/parent level. For items with variants (e.g., T-Shirt), child SKUs are in POS_ITEM_VARIANTS.';
COMMENT ON COLUMN POS_ITEMS.HAS_VARIANTS IS 'Y if item has size/color matrix variants stored in POS_ITEM_VARIANTS.';
COMMENT ON COLUMN POS_ITEMS.HAS_SERIAL IS 'Y if each unit has a unique serial number tracked in POS_LOT_SERIAL_CONTROL.';
COMMENT ON COLUMN POS_ITEMS.HAS_LOT IS 'Y if items are tracked in batches/lots with expiry dates.';
COMMENT ON COLUMN POS_ITEMS.IS_WEIGHABLE IS 'Y for items sold by weight (scale integration). QUANTITY is entered from scale reading.';
COMMENT ON COLUMN POS_ITEMS.IS_OPEN_PRICE IS 'Y if cashier can enter any price (e.g., custom service charges).';
COMMENT ON COLUMN POS_ITEMS.KDS_CATEGORY IS 'Category label for Kitchen Display System grouping (e.g., HOT_FOOD, COLD_DRINKS).';

CREATE INDEX POS_IT_CAT_IDX     ON POS_ITEMS(CATEGORY_ID);
CREATE INDEX POS_IT_BARCODE_IDX ON POS_ITEMS(BARCODE);
CREATE INDEX POS_IT_ALT_BC_IDX  ON POS_ITEMS(ALT_BARCODE);
CREATE INDEX POS_IT_SECTOR_IDX  ON POS_ITEMS(SECTOR_TYPE);
CREATE INDEX POS_IT_ACTIVE_IDX  ON POS_ITEMS(IS_ACTIVE);

-- ==========================================================================
-- TABLE 4: POS_ITEM_ATTRIBUTES
-- ==========================================================================
CREATE TABLE POS_ITEM_ATTRIBUTES (
    ATTRIBUTE_ID            NUMBER          DEFAULT SEQ_ATTRIBUTE_ID.NEXTVAL NOT NULL,
    ATTRIBUTE_CODE          VARCHAR2(30)    NOT NULL,
    ATTRIBUTE_NAME_EN       VARCHAR2(100)   NOT NULL,
    ATTRIBUTE_NAME_AR       VARCHAR2(100),
    DISPLAY_ORDER           NUMBER          DEFAULT 10,
    IS_ACTIVE               CHAR(1)         DEFAULT 'Y' NOT NULL,
    CONSTRAINT POS_IA_PK        PRIMARY KEY (ATTRIBUTE_ID),
    CONSTRAINT POS_IA_CODE_UK   UNIQUE (ATTRIBUTE_CODE),
    CONSTRAINT POS_IA_ACTIVE_CHK CHECK (IS_ACTIVE IN ('Y','N'))
);

COMMENT ON TABLE POS_ITEM_ATTRIBUTES IS 'Defines variant dimensions like SIZE, COLOR, MATERIAL, FLAVOR, etc.';

-- Seed standard attributes
INSERT INTO POS_ITEM_ATTRIBUTES(ATTRIBUTE_ID,ATTRIBUTE_CODE,ATTRIBUTE_NAME_EN,ATTRIBUTE_NAME_AR,DISPLAY_ORDER)
VALUES(SEQ_ATTRIBUTE_ID.NEXTVAL,'SIZE','Size','الحجم',1);
INSERT INTO POS_ITEM_ATTRIBUTES(ATTRIBUTE_ID,ATTRIBUTE_CODE,ATTRIBUTE_NAME_EN,ATTRIBUTE_NAME_AR,DISPLAY_ORDER)
VALUES(SEQ_ATTRIBUTE_ID.NEXTVAL,'COLOR','Color','اللون',2);
INSERT INTO POS_ITEM_ATTRIBUTES(ATTRIBUTE_ID,ATTRIBUTE_CODE,ATTRIBUTE_NAME_EN,ATTRIBUTE_NAME_AR,DISPLAY_ORDER)
VALUES(SEQ_ATTRIBUTE_ID.NEXTVAL,'FLAVOR','Flavor','النكهة',3);
COMMIT;

-- ==========================================================================
-- TABLE 5: POS_ATTRIBUTE_VALUES
-- ==========================================================================
CREATE TABLE POS_ATTRIBUTE_VALUES (
    ATTRIBUTE_VALUE_ID      NUMBER          DEFAULT SEQ_ATTRIBUTE_VALUE_ID.NEXTVAL NOT NULL,
    ATTRIBUTE_ID            NUMBER          NOT NULL,
    VALUE_CODE              VARCHAR2(50)    NOT NULL,
    VALUE_NAME_EN           VARCHAR2(100)   NOT NULL,
    VALUE_NAME_AR           VARCHAR2(100),
    SORT_ORDER              NUMBER          DEFAULT 10,
    IS_ACTIVE               CHAR(1)         DEFAULT 'Y' NOT NULL,
    CONSTRAINT POS_AV_PK        PRIMARY KEY (ATTRIBUTE_VALUE_ID),
    CONSTRAINT POS_AV_UK        UNIQUE (ATTRIBUTE_ID, VALUE_CODE),
    CONSTRAINT POS_AV_ATTR_FK   FOREIGN KEY (ATTRIBUTE_ID) REFERENCES POS_ITEM_ATTRIBUTES(ATTRIBUTE_ID),
    CONSTRAINT POS_AV_ACTIVE_CHK CHECK (IS_ACTIVE IN ('Y','N'))
);

COMMENT ON TABLE POS_ATTRIBUTE_VALUES IS 'Valid values for each item attribute. e.g., SIZE -> S, M, L, XL; COLOR -> Red, Blue, Black.';

CREATE INDEX POS_AV_ATTR_IDX ON POS_ATTRIBUTE_VALUES(ATTRIBUTE_ID);

-- ==========================================================================
-- TABLE 6: POS_ITEM_VARIANTS
-- ==========================================================================
CREATE TABLE POS_ITEM_VARIANTS (
    VARIANT_ID              NUMBER          DEFAULT SEQ_VARIANT_ID.NEXTVAL NOT NULL,
    ITEM_ID                 NUMBER          NOT NULL,
    SKU_CODE                VARCHAR2(100)   NOT NULL,
    VARIANT_NAME_EN         VARCHAR2(240),
    VARIANT_NAME_AR         VARCHAR2(240),
    BARCODE                 VARCHAR2(100),
    BARCODE2                VARCHAR2(100),
    IMAGE_URL               VARCHAR2(500),
    WEIGHT_VALUE            NUMBER(10,4),
    COST_PRICE              NUMBER(18,6),
    PRICE_ADJUSTMENT        NUMBER(18,6)    DEFAULT 0,
    IS_ACTIVE               CHAR(1)         DEFAULT 'Y' NOT NULL,
    CREATED_BY              NUMBER,
    CREATION_DATE           DATE            DEFAULT SYSDATE,
    LAST_UPDATED_BY         NUMBER,
    LAST_UPDATE_DATE        DATE,
    CONSTRAINT POS_IV_PK        PRIMARY KEY (VARIANT_ID),
    CONSTRAINT POS_IV_SKU_UK    UNIQUE (SKU_CODE),
    CONSTRAINT POS_IV_ITEM_FK   FOREIGN KEY (ITEM_ID) REFERENCES POS_ITEMS(ITEM_ID),
    CONSTRAINT POS_IV_ACTIVE_CHK CHECK (IS_ACTIVE IN ('Y','N'))
);

COMMENT ON TABLE POS_ITEM_VARIANTS IS 'SKU-level variants of an item (e.g., Blue T-Shirt Size M). Each variant has its own barcode and optional cost override.';
COMMENT ON COLUMN POS_ITEM_VARIANTS.PRICE_ADJUSTMENT IS 'Amount to add/subtract from base item price for this variant. Can be positive or negative.';

CREATE INDEX POS_IV_ITEM_IDX    ON POS_ITEM_VARIANTS(ITEM_ID);
CREATE INDEX POS_IV_BARCODE_IDX ON POS_ITEM_VARIANTS(BARCODE);
CREATE INDEX POS_IV_BARCD2_IDX  ON POS_ITEM_VARIANTS(BARCODE2);
CREATE INDEX POS_IV_ACTIVE_IDX  ON POS_ITEM_VARIANTS(IS_ACTIVE);

-- ==========================================================================
-- TABLE 7: POS_VARIANT_ATTRIBUTE_VALS
-- ==========================================================================
CREATE TABLE POS_VARIANT_ATTRIBUTE_VALS (
    VAV_ID                  NUMBER          DEFAULT SEQ_VAV_ID.NEXTVAL NOT NULL,
    VARIANT_ID              NUMBER          NOT NULL,
    ATTRIBUTE_ID            NUMBER          NOT NULL,
    ATTRIBUTE_VALUE_ID      NUMBER          NOT NULL,
    CONSTRAINT POS_VAV_PK       PRIMARY KEY (VAV_ID),
    CONSTRAINT POS_VAV_UK       UNIQUE (VARIANT_ID, ATTRIBUTE_ID),
    CONSTRAINT POS_VAV_VAR_FK   FOREIGN KEY (VARIANT_ID) REFERENCES POS_ITEM_VARIANTS(VARIANT_ID),
    CONSTRAINT POS_VAV_ATTR_FK  FOREIGN KEY (ATTRIBUTE_ID) REFERENCES POS_ITEM_ATTRIBUTES(ATTRIBUTE_ID),
    CONSTRAINT POS_VAV_VAL_FK   FOREIGN KEY (ATTRIBUTE_VALUE_ID) REFERENCES POS_ATTRIBUTE_VALUES(ATTRIBUTE_VALUE_ID)
);

COMMENT ON TABLE POS_VARIANT_ATTRIBUTE_VALS IS 'Intersection: assigns attribute values to variants. e.g., Variant 501 has Color=Blue AND Size=M.';

CREATE INDEX POS_VAV_VAR_IDX  ON POS_VARIANT_ATTRIBUTE_VALS(VARIANT_ID);
CREATE INDEX POS_VAV_ATTR_IDX ON POS_VARIANT_ATTRIBUTE_VALS(ATTRIBUTE_ID);

-- ==========================================================================
-- TABLE 8: POS_ITEM_ORG_ASSIGN
-- ==========================================================================
CREATE TABLE POS_ITEM_ORG_ASSIGN (
    ASSIGNMENT_ID           NUMBER          DEFAULT SEQ_ITEM_ORG_ASSIGN_ID.NEXTVAL NOT NULL,
    ITEM_ID                 NUMBER          NOT NULL,
    INV_ORG_ID              NUMBER          NOT NULL,
    IS_PURCHASABLE          CHAR(1)         DEFAULT 'Y',
    IS_SELLABLE             CHAR(1)         DEFAULT 'Y',
    IS_STOCKABLE            CHAR(1)         DEFAULT 'Y',
    MIN_ORDER_QTY           NUMBER(18,6)    DEFAULT 0,
    MAX_ORDER_QTY           NUMBER(18,6),
    REORDER_POINT           NUMBER(18,6),
    REORDER_QTY             NUMBER(18,6),
    LEAD_TIME_DAYS          NUMBER          DEFAULT 0,
    SHELF_LIFE_DAYS         NUMBER,
    PRIMARY_SUBINV_ID       NUMBER,
    IS_ACTIVE               CHAR(1)         DEFAULT 'Y' NOT NULL,
    CREATED_BY              NUMBER,
    CREATION_DATE           DATE            DEFAULT SYSDATE,
    LAST_UPDATED_BY         NUMBER,
    LAST_UPDATE_DATE        DATE,
    CONSTRAINT POS_IOA_PK       PRIMARY KEY (ASSIGNMENT_ID),
    CONSTRAINT POS_IOA_UK       UNIQUE (ITEM_ID, INV_ORG_ID),
    CONSTRAINT POS_IOA_ITEM_FK  FOREIGN KEY (ITEM_ID) REFERENCES POS_ITEMS(ITEM_ID),
    CONSTRAINT POS_IOA_ORG_FK   FOREIGN KEY (INV_ORG_ID) REFERENCES POS_INVENTORY_ORGS(INV_ORG_ID),
    CONSTRAINT POS_IOA_ACTIVE_CHK CHECK (IS_ACTIVE IN ('Y','N'))
);

COMMENT ON TABLE POS_ITEM_ORG_ASSIGN IS 'Assigns items to Inventory Orgs. Item must be assigned before it can be sold/stocked in an org.';
COMMENT ON COLUMN POS_ITEM_ORG_ASSIGN.REORDER_POINT IS 'Minimum on-hand qty threshold that triggers a reorder alert or auto-PO.';
COMMENT ON COLUMN POS_ITEM_ORG_ASSIGN.PRIMARY_SUBINV_ID IS 'Default subinventory for this item in this org during receipts.';

CREATE INDEX POS_IOA_ITEM_IDX ON POS_ITEM_ORG_ASSIGN(ITEM_ID);
CREATE INDEX POS_IOA_ORG_IDX  ON POS_ITEM_ORG_ASSIGN(INV_ORG_ID);

-- ==========================================================================
-- TABLE 9: POS_LOT_SERIAL_CONTROL
-- ==========================================================================
CREATE TABLE POS_LOT_SERIAL_CONTROL (
    LOT_SERIAL_ID           NUMBER          DEFAULT SEQ_LOT_SERIAL_ID.NEXTVAL NOT NULL,
    ITEM_ID                 NUMBER          NOT NULL,
    VARIANT_ID              NUMBER,
    INV_ORG_ID              NUMBER          NOT NULL,
    SUBINV_ID               NUMBER,
    CONTROL_TYPE            CHAR(1)         NOT NULL,
    LOT_SERIAL_NUMBER       VARCHAR2(100)   NOT NULL,
    MANUFACTURING_DATE      DATE,
    EXPIRY_DATE             DATE,
    RECEIVED_DATE           DATE            DEFAULT SYSDATE,
    SUPPLIER_LOT_NO         VARCHAR2(100),
    QUANTITY_ON_HAND        NUMBER(18,6)    DEFAULT 0,
    QUANTITY_RESERVED       NUMBER(18,6)    DEFAULT 0,
    STATUS                  VARCHAR2(20)    DEFAULT 'ACTIVE' NOT NULL,
    QUARANTINE_REASON       VARCHAR2(500),
    CREATED_BY              NUMBER,
    CREATION_DATE           DATE            DEFAULT SYSDATE,
    LAST_UPDATED_BY         NUMBER,
    LAST_UPDATE_DATE        DATE,
    CONSTRAINT POS_LSC_PK       PRIMARY KEY (LOT_SERIAL_ID),
    CONSTRAINT POS_LSC_UK       UNIQUE (ITEM_ID, INV_ORG_ID, CONTROL_TYPE, LOT_SERIAL_NUMBER),
    CONSTRAINT POS_LSC_ITEM_FK  FOREIGN KEY (ITEM_ID) REFERENCES POS_ITEMS(ITEM_ID),
    CONSTRAINT POS_LSC_VAR_FK   FOREIGN KEY (VARIANT_ID) REFERENCES POS_ITEM_VARIANTS(VARIANT_ID),
    CONSTRAINT POS_LSC_ORG_FK   FOREIGN KEY (INV_ORG_ID) REFERENCES POS_INVENTORY_ORGS(INV_ORG_ID),
    CONSTRAINT POS_LSC_TYPE_CHK CHECK (CONTROL_TYPE IN ('L','S')),
    CONSTRAINT POS_LSC_STATUS_CHK CHECK (STATUS IN ('ACTIVE','EXPIRED','QUARANTINE','CONSUMED'))
);

COMMENT ON TABLE POS_LOT_SERIAL_CONTROL IS 'Lot and Serial number registry with full traceability: expiry, supplier lot, quantities.';
COMMENT ON COLUMN POS_LOT_SERIAL_CONTROL.CONTROL_TYPE IS 'L=Lot/Batch tracking, S=Serial number tracking (unique per unit).';
COMMENT ON COLUMN POS_LOT_SERIAL_CONTROL.QUANTITY_ON_HAND IS 'Current qty for this lot (always 0 or 1 for serials).';

CREATE INDEX POS_LSC_ITEM_IDX   ON POS_LOT_SERIAL_CONTROL(ITEM_ID);
CREATE INDEX POS_LSC_ORG_IDX    ON POS_LOT_SERIAL_CONTROL(INV_ORG_ID);
CREATE INDEX POS_LSC_EXPIRY_IDX ON POS_LOT_SERIAL_CONTROL(EXPIRY_DATE);
CREATE INDEX POS_LSC_STATUS_IDX ON POS_LOT_SERIAL_CONTROL(STATUS);

-- END OF FILE: 02_item_master.sql
