-- ==============================================================================
-- FILE 1: 03_pricing_and_promotions.sql
-- Description: DDL for Pricing, Promotions, Coupons, and Loyalty
-- ==============================================================================

-- Sequences
CREATE SEQUENCE pos_price_lists_seq START WITH 1 NOCACHE;
CREATE SEQUENCE pos_price_list_lines_seq START WITH 1 NOCACHE;
CREATE SEQUENCE pos_cust_price_list_seq START WITH 1 NOCACHE;
CREATE SEQUENCE pos_promotions_seq START WITH 1 NOCACHE;
CREATE SEQUENCE pos_promo_items_seq START WITH 1 NOCACHE;
CREATE SEQUENCE pos_coupons_seq START WITH 1 NOCACHE;
CREATE SEQUENCE pos_loyalty_programs_seq START WITH 1 NOCACHE;
CREATE SEQUENCE pos_loyalty_accounts_seq START WITH 1 NOCACHE;
CREATE SEQUENCE pos_loyalty_txns_seq START WITH 1 NOCACHE;

-- 1. POS_PRICE_LISTS
CREATE TABLE POS_PRICE_LISTS (
    PRICE_LIST_ID NUMBER DEFAULT pos_price_lists_seq.NEXTVAL PRIMARY KEY,
    PRICE_LIST_CODE VARCHAR2(30) NOT NULL UNIQUE,
    PRICE_LIST_NAME VARCHAR2(240) NOT NULL,
    PRICE_LIST_TYPE VARCHAR2(20) CHECK (PRICE_LIST_TYPE IN ('STANDARD','CUSTOMER_TIER','SEASONAL','BRANCH_SPECIFIC','PROMOTIONAL')),
    CURRENCY_CODE VARCHAR2(3) NOT NULL,
    INV_ORG_ID NUMBER, -- FK nullable
    PARENT_PRICE_LIST_ID NUMBER REFERENCES POS_PRICE_LISTS(PRICE_LIST_ID),
    PRIORITY NUMBER(3) DEFAULT 100,
    START_DATE DATE,
    END_DATE DATE,
    IS_ACTIVE CHAR(1),
    CREATED_BY NUMBER,
    CREATION_DATE DATE DEFAULT SYSDATE,
    LAST_UPDATED_BY NUMBER,
    LAST_UPDATE_DATE DATE
);

CREATE INDEX pos_prc_lst_org_idx ON POS_PRICE_LISTS(INV_ORG_ID);
CREATE INDEX pos_prc_lst_parent_idx ON POS_PRICE_LISTS(PARENT_PRICE_LIST_ID);

-- 2. POS_PRICE_LIST_LINES
CREATE TABLE POS_PRICE_LIST_LINES (
    PRICE_LINE_ID NUMBER DEFAULT pos_price_list_lines_seq.NEXTVAL PRIMARY KEY,
    PRICE_LIST_ID NUMBER NOT NULL REFERENCES POS_PRICE_LISTS(PRICE_LIST_ID),
    ITEM_ID NUMBER NOT NULL, -- FK
    VARIANT_ID NUMBER,       -- FK nullable
    UOM_CODE VARCHAR2(10) NOT NULL, -- FK
    LIST_PRICE NUMBER(18,6) NOT NULL,
    MIN_PRICE NUMBER(18,6),
    MAX_PRICE NUMBER(18,6),
    START_DATE DATE,
    END_DATE DATE,
    IS_ACTIVE CHAR(1),
    CREATED_BY NUMBER,
    CREATION_DATE DATE DEFAULT SYSDATE,
    LAST_UPDATED_BY NUMBER,
    LAST_UPDATE_DATE DATE,
    CONSTRAINT pos_prc_lst_ln_uk UNIQUE (PRICE_LIST_ID, ITEM_ID, VARIANT_ID, UOM_CODE)
);

CREATE INDEX pos_prc_lst_ln_item_idx ON POS_PRICE_LIST_LINES(ITEM_ID);

-- 3. POS_CUSTOMER_PRICE_LIST
CREATE TABLE POS_CUSTOMER_PRICE_LIST (
    CUSTOMER_PRICE_ID NUMBER DEFAULT pos_cust_price_list_seq.NEXTVAL PRIMARY KEY,
    CUSTOMER_ID NUMBER NOT NULL, -- FK -> POS_CUSTOMERS
    PRICE_LIST_ID NUMBER NOT NULL REFERENCES POS_PRICE_LISTS(PRICE_LIST_ID),
    START_DATE DATE,
    END_DATE DATE,
    CREATED_BY NUMBER,
    CREATION_DATE DATE DEFAULT SYSDATE,
    LAST_UPDATED_BY NUMBER,
    LAST_UPDATE_DATE DATE
);

CREATE INDEX pos_cust_prc_lst_cust_idx ON POS_CUSTOMER_PRICE_LIST(CUSTOMER_ID);
CREATE INDEX pos_cust_prc_lst_prc_idx ON POS_CUSTOMER_PRICE_LIST(PRICE_LIST_ID);

-- 4. POS_PROMOTIONS
CREATE TABLE POS_PROMOTIONS (
    PROMO_ID NUMBER DEFAULT pos_promotions_seq.NEXTVAL PRIMARY KEY,
    PROMO_CODE VARCHAR2(50) NOT NULL UNIQUE,
    PROMO_NAME VARCHAR2(240),
    PROMO_TYPE VARCHAR2(30) CHECK (PROMO_TYPE IN ('PERCENT_DISCOUNT','FIXED_DISCOUNT','BXGY','BUNDLE','THRESHOLD','FREE_ITEM','LOYALTY_POINTS')),
    INV_ORG_ID NUMBER, -- FK nullable
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
    MIN_ORDER_AMOUNT NUMBER(18,2),
    MAX_USES_TOTAL NUMBER,
    MAX_USES_PER_CUSTOMER NUMBER,
    CURRENT_USE_COUNT NUMBER DEFAULT 0,
    DISCOUNT_PERCENT NUMBER(7,4),
    DISCOUNT_AMOUNT NUMBER(18,2),
    BUY_ITEM_ID NUMBER, -- FK nullable
    BUY_QTY NUMBER,
    GET_ITEM_ID NUMBER, -- FK nullable
    GET_QTY NUMBER,
    GET_DISCOUNT_PERCENT NUMBER(7,4) DEFAULT 100,
    THRESHOLD_AMOUNT NUMBER(18,2),
    LOYALTY_POINTS_EARNED NUMBER,
    IS_STACKABLE CHAR(1) DEFAULT 'N',
    IS_ACTIVE CHAR(1),
    CREATED_BY NUMBER,
    CREATION_DATE DATE DEFAULT SYSDATE,
    LAST_UPDATED_BY NUMBER,
    LAST_UPDATE_DATE DATE
);

CREATE INDEX pos_promo_org_idx ON POS_PROMOTIONS(INV_ORG_ID);

-- 5. POS_PROMO_ITEMS
CREATE TABLE POS_PROMO_ITEMS (
    PROMO_ITEM_ID NUMBER DEFAULT pos_promo_items_seq.NEXTVAL PRIMARY KEY,
    PROMO_ID NUMBER NOT NULL REFERENCES POS_PROMOTIONS(PROMO_ID),
    ITEM_ID NUMBER, -- FK
    CATEGORY_ID NUMBER, -- FK
    ITEM_ROLE VARCHAR2(20) CHECK (ITEM_ROLE IN ('BUY','GET','QUALIFYING','EXCLUDED')),
    CREATED_BY NUMBER,
    CREATION_DATE DATE DEFAULT SYSDATE,
    LAST_UPDATED_BY NUMBER,
    LAST_UPDATE_DATE DATE
);

CREATE INDEX pos_promo_items_promo_idx ON POS_PROMO_ITEMS(PROMO_ID);
CREATE INDEX pos_promo_items_item_idx ON POS_PROMO_ITEMS(ITEM_ID);

-- 6. POS_COUPONS
CREATE TABLE POS_COUPONS (
    COUPON_ID NUMBER DEFAULT pos_coupons_seq.NEXTVAL PRIMARY KEY,
    COUPON_CODE VARCHAR2(50) NOT NULL UNIQUE,
    PROMO_ID NUMBER NOT NULL REFERENCES POS_PROMOTIONS(PROMO_ID),
    CUSTOMER_ID NUMBER, -- FK nullable
    MAX_USES NUMBER DEFAULT 1,
    CURRENT_USES NUMBER DEFAULT 0,
    EXPIRY_DATE DATE,
    IS_ACTIVE CHAR(1),
    CREATED_BY NUMBER,
    CREATION_DATE DATE DEFAULT SYSDATE,
    LAST_UPDATED_BY NUMBER,
    LAST_UPDATE_DATE DATE
);

CREATE INDEX pos_coupons_promo_idx ON POS_COUPONS(PROMO_ID);
CREATE INDEX pos_coupons_cust_idx ON POS_COUPONS(CUSTOMER_ID);

-- 7. POS_LOYALTY_PROGRAMS
CREATE TABLE POS_LOYALTY_PROGRAMS (
    PROGRAM_ID NUMBER DEFAULT pos_loyalty_programs_seq.NEXTVAL PRIMARY KEY,
    PROGRAM_CODE VARCHAR2(30) NOT NULL UNIQUE,
    PROGRAM_NAME VARCHAR2(240) NOT NULL,
    POINTS_PER_CURRENCY_UNIT NUMBER(10,4) DEFAULT 1,
    CURRENCY_PER_POINT NUMBER(10,4) DEFAULT 0.01,
    MIN_REDEEM_POINTS NUMBER DEFAULT 100,
    MAX_REDEEM_PERCENT NUMBER(5,2) DEFAULT 50,
    EXPIRY_MONTHS NUMBER DEFAULT 12,
    IS_ACTIVE CHAR(1),
    CREATED_BY NUMBER,
    CREATION_DATE DATE DEFAULT SYSDATE,
    LAST_UPDATED_BY NUMBER,
    LAST_UPDATE_DATE DATE
);

-- 8. POS_LOYALTY_ACCOUNTS
CREATE TABLE POS_LOYALTY_ACCOUNTS (
    LOYALTY_ACCOUNT_ID NUMBER DEFAULT pos_loyalty_accounts_seq.NEXTVAL PRIMARY KEY,
    CUSTOMER_ID NUMBER NOT NULL UNIQUE, -- FK -> POS_CUSTOMERS
    PROGRAM_ID NUMBER NOT NULL REFERENCES POS_LOYALTY_PROGRAMS(PROGRAM_ID),
    POINTS_BALANCE NUMBER DEFAULT 0,
    LIFETIME_POINTS_EARNED NUMBER DEFAULT 0,
    LIFETIME_POINTS_REDEEMED NUMBER DEFAULT 0,
    TIER_CODE VARCHAR2(20) DEFAULT 'STANDARD',
    TIER_VALID_UNTIL DATE,
    CREATED_BY NUMBER,
    CREATION_DATE DATE DEFAULT SYSDATE,
    LAST_UPDATED_BY NUMBER,
    LAST_UPDATE_DATE DATE
);

CREATE INDEX pos_loy_acc_prog_idx ON POS_LOYALTY_ACCOUNTS(PROGRAM_ID);

-- 9. POS_LOYALTY_TRANSACTIONS
CREATE TABLE POS_LOYALTY_TRANSACTIONS (
    LOYALTY_TXN_ID NUMBER DEFAULT pos_loyalty_txns_seq.NEXTVAL PRIMARY KEY,
    LOYALTY_ACCOUNT_ID NUMBER NOT NULL REFERENCES POS_LOYALTY_ACCOUNTS(LOYALTY_ACCOUNT_ID),
    ORDER_ID NUMBER, -- FK nullable -> POS_ORDERS
    TXN_TYPE VARCHAR2(20) CHECK (TXN_TYPE IN ('EARN','REDEEM','EXPIRE','ADJUST','TRANSFER')),
    POINTS NUMBER NOT NULL,
    POINTS_BEFORE NUMBER,
    POINTS_AFTER NUMBER,
    NOTES VARCHAR2(500),
    TXN_DATE DATE DEFAULT SYSDATE,
    CREATED_BY NUMBER,
    CREATION_DATE DATE DEFAULT SYSDATE,
    LAST_UPDATED_BY NUMBER,
    LAST_UPDATE_DATE DATE
);

CREATE INDEX pos_loy_txn_acc_idx ON POS_LOYALTY_TRANSACTIONS(LOYALTY_ACCOUNT_ID);
CREATE INDEX pos_loy_txn_ord_idx ON POS_LOYALTY_TRANSACTIONS(ORDER_ID);

-- END OF FILE
