-- ==============================================================================
-- FILE 2: 04_orders_and_payments.sql
-- Description: DDL for Customers, Orders, Shifts, and Payments
-- ==============================================================================

-- Sequences
CREATE SEQUENCE pos_customers_seq START WITH 1 NOCACHE;
CREATE SEQUENCE pos_shifts_seq START WITH 1 NOCACHE;
CREATE SEQUENCE pos_shift_cash_mov_seq START WITH 1 NOCACHE;
CREATE SEQUENCE pos_tables_seq START WITH 1 NOCACHE;
CREATE SEQUENCE pos_orders_seq START WITH 1 NOCACHE;
CREATE SEQUENCE pos_order_lines_seq START WITH 1 NOCACHE;
CREATE SEQUENCE pos_payment_methods_seq START WITH 1 NOCACHE;
CREATE SEQUENCE pos_order_payments_seq START WITH 1 NOCACHE;

-- 1. POS_CUSTOMERS
CREATE TABLE POS_CUSTOMERS (
    CUSTOMER_ID NUMBER DEFAULT pos_customers_seq.NEXTVAL PRIMARY KEY,
    CUSTOMER_CODE VARCHAR2(50) NOT NULL UNIQUE,
    CUSTOMER_NAME_AR VARCHAR2(240),
    CUSTOMER_NAME_EN VARCHAR2(240) NOT NULL,
    CUSTOMER_TYPE VARCHAR2(20) CHECK (CUSTOMER_TYPE IN ('INDIVIDUAL','COMPANY','GOVERNMENT','WALK_IN')),
    TAX_REGISTRATION_NO VARCHAR2(50),
    NATIONAL_ID VARCHAR2(50),
    EMAIL VARCHAR2(240),
    PHONE VARCHAR2(50),
    ALT_PHONE VARCHAR2(50),
    ADDRESS_LINE1 VARCHAR2(240),
    ADDRESS_LINE2 VARCHAR2(240),
    CITY VARCHAR2(100),
    COUNTRY_CODE VARCHAR2(5),
    CREDIT_LIMIT NUMBER(18,2) DEFAULT 0,
    CREDIT_USED NUMBER(18,2) DEFAULT 0,
    PAYMENT_TERMS VARCHAR2(20) DEFAULT 'CASH',
    INV_ORG_ID NUMBER NOT NULL, -- FK
    IS_ACTIVE CHAR(1),
    CREATED_BY NUMBER,
    CREATION_DATE DATE DEFAULT SYSDATE,
    LAST_UPDATED_BY NUMBER,
    LAST_UPDATE_DATE DATE
);

CREATE INDEX pos_customers_org_idx ON POS_CUSTOMERS(INV_ORG_ID);

-- 2. POS_SHIFTS
CREATE TABLE POS_SHIFTS (
    SHIFT_ID NUMBER DEFAULT pos_shifts_seq.NEXTVAL PRIMARY KEY,
    SHIFT_NO VARCHAR2(30) NOT NULL UNIQUE,
    TERMINAL_ID NUMBER NOT NULL, -- FK
    INV_ORG_ID NUMBER NOT NULL,  -- FK
    CASHIER_USER_ID NUMBER NOT NULL, -- FK -> POS_APP_USERS
    SUPERVISOR_USER_ID NUMBER,       -- FK nullable
    SHIFT_STATUS VARCHAR2(20) CHECK (SHIFT_STATUS IN ('OPEN','SUSPENDED','CLOSED','RECONCILED')),
    OPEN_DATETIME TIMESTAMP NOT NULL,
    CLOSE_DATETIME TIMESTAMP,
    OPENING_FLOAT NUMBER(18,2) DEFAULT 0,
    EXPECTED_CASH NUMBER(18,2) DEFAULT 0,
    DECLARED_CASH NUMBER(18,2) DEFAULT 0,
    OVER_SHORT_AMOUNT NUMBER(18,2),
    TOTAL_SALES NUMBER(18,2) DEFAULT 0,
    TOTAL_REFUNDS NUMBER(18,2) DEFAULT 0,
    TOTAL_VOIDS NUMBER(18,2) DEFAULT 0,
    TOTAL_DISCOUNTS NUMBER(18,2) DEFAULT 0,
    TOTAL_TAX NUMBER(18,2) DEFAULT 0,
    TOTAL_CASH_IN NUMBER(18,2) DEFAULT 0,
    TOTAL_CASH_OUT NUMBER(18,2) DEFAULT 0,
    CLOSE_NOTES VARCHAR2(1000),
    Z_REPORT_PRINTED CHAR(1) DEFAULT 'N',
    CREATED_BY NUMBER,
    CREATION_DATE DATE DEFAULT SYSDATE,
    LAST_UPDATED_BY NUMBER,
    LAST_UPDATE_DATE DATE
);

CREATE INDEX pos_shifts_terminal_idx ON POS_SHIFTS(TERMINAL_ID);
CREATE INDEX pos_shifts_cashier_idx ON POS_SHIFTS(CASHIER_USER_ID);

-- 3. POS_SHIFT_CASH_MOVEMENTS
CREATE TABLE POS_SHIFT_CASH_MOVEMENTS (
    MOVEMENT_ID NUMBER DEFAULT pos_shift_cash_mov_seq.NEXTVAL PRIMARY KEY,
    SHIFT_ID NUMBER NOT NULL REFERENCES POS_SHIFTS(SHIFT_ID),
    MOVEMENT_TYPE VARCHAR2(20) CHECK (MOVEMENT_TYPE IN ('PAID_IN','PAID_OUT','CASH_DROP','OPENING_FLOAT','VOID_REFUND')),
    AMOUNT NUMBER(18,2) NOT NULL,
    REASON VARCHAR2(500),
    AUTHORIZED_BY NUMBER,
    MOVEMENT_DATETIME TIMESTAMP DEFAULT SYSTIMESTAMP,
    RECEIPT_NO VARCHAR2(50),
    CREATED_BY NUMBER,
    CREATION_DATE DATE DEFAULT SYSDATE,
    LAST_UPDATED_BY NUMBER,
    LAST_UPDATE_DATE DATE
);

CREATE INDEX pos_shf_csh_mov_shf_idx ON POS_SHIFT_CASH_MOVEMENTS(SHIFT_ID);

-- 4. POS_TABLES
CREATE TABLE POS_TABLES (
    TABLE_ID NUMBER DEFAULT pos_tables_seq.NEXTVAL PRIMARY KEY,
    TABLE_CODE VARCHAR2(20) NOT NULL,
    TABLE_NAME VARCHAR2(50),
    INV_ORG_ID NUMBER NOT NULL, -- FK
    FLOOR_NO NUMBER DEFAULT 1,
    SECTION_NAME VARCHAR2(50),
    CAPACITY NUMBER,
    TABLE_STATUS VARCHAR2(20) CHECK (TABLE_STATUS IN ('AVAILABLE','OCCUPIED','RESERVED','CLEANING','INACTIVE')),
    CURRENT_ORDER_ID NUMBER, -- FK -> POS_ORDERS (created later, constraint added below or omitted)
    X_POSITION NUMBER,
    Y_POSITION NUMBER,
    IS_ACTIVE CHAR(1),
    CREATED_BY NUMBER,
    CREATION_DATE DATE DEFAULT SYSDATE,
    LAST_UPDATED_BY NUMBER,
    LAST_UPDATE_DATE DATE,
    CONSTRAINT pos_tables_org_code_uk UNIQUE (INV_ORG_ID, TABLE_CODE)
);

-- 5. POS_ORDERS
CREATE TABLE POS_ORDERS (
    ORDER_ID NUMBER DEFAULT pos_orders_seq.NEXTVAL PRIMARY KEY,
    ORDER_NO VARCHAR2(30) NOT NULL UNIQUE,
    INV_ORG_ID NUMBER NOT NULL, -- FK
    TERMINAL_ID NUMBER,         -- FK
    SHIFT_ID NUMBER NOT NULL REFERENCES POS_SHIFTS(SHIFT_ID),
    CASHIER_USER_ID NUMBER NOT NULL, -- FK
    CUSTOMER_ID NUMBER REFERENCES POS_CUSTOMERS(CUSTOMER_ID),
    TABLE_ID NUMBER REFERENCES POS_TABLES(TABLE_ID),
    ORDER_TYPE VARCHAR2(20) CHECK (ORDER_TYPE IN ('SALE','RETURN','EXCHANGE','HOLD','LAYAWAY','QUOTATION')),
    ORDER_STATUS VARCHAR2(20) CHECK (ORDER_STATUS IN ('DRAFT','CONFIRMED','PARTIALLY_PAID','PAID','VOIDED','REFUNDED','SENT_TO_KDS')),
    SECTOR_TYPE VARCHAR2(20) CHECK (SECTOR_TYPE IN ('RETAIL','FNB','SERVICE')),
    ORDER_DATETIME TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONFIRMED_DATETIME TIMESTAMP,
    SUBTOTAL NUMBER(18,2) DEFAULT 0,
    DISCOUNT_AMOUNT NUMBER(18,2) DEFAULT 0,
    TAX_AMOUNT NUMBER(18,2) DEFAULT 0,
    ROUNDING_AMOUNT NUMBER(18,4) DEFAULT 0,
    TOTAL_AMOUNT NUMBER(18,2) DEFAULT 0,
    PAID_AMOUNT NUMBER(18,2) DEFAULT 0,
    CHANGE_AMOUNT NUMBER(18,2) DEFAULT 0,
    CURRENCY_CODE VARCHAR2(3) NOT NULL,
    EXCHANGE_RATE NUMBER(18,8) DEFAULT 1,
    PRICE_LIST_ID NUMBER, -- FK
    PROMO_ID NUMBER,      -- FK
    COUPON_ID NUMBER,     -- FK
    LOYALTY_POINTS_EARNED NUMBER DEFAULT 0,
    LOYALTY_POINTS_REDEEMED NUMBER DEFAULT 0,
    NOTES VARCHAR2(1000),
    REFERENCE_ORDER_ID NUMBER REFERENCES POS_ORDERS(ORDER_ID),
    IS_OFFLINE CHAR(1) DEFAULT 'N',
    OFFLINE_IDEMPOTENCY_KEY VARCHAR2(100) UNIQUE,
    KDS_STATUS VARCHAR2(20),
    KDS_SENT_DATETIME TIMESTAMP,
    CREATED_BY NUMBER,
    CREATION_DATE DATE DEFAULT SYSDATE,
    LAST_UPDATED_BY NUMBER,
    LAST_UPDATE_DATE DATE
);

CREATE INDEX pos_orders_org_idx ON POS_ORDERS(INV_ORG_ID);
CREATE INDEX pos_orders_shift_idx ON POS_ORDERS(SHIFT_ID);
CREATE INDEX pos_orders_cust_idx ON POS_ORDERS(CUSTOMER_ID);

-- Adding FK back to tables now that orders exist
ALTER TABLE POS_TABLES ADD CONSTRAINT pos_tables_ord_fk FOREIGN KEY (CURRENT_ORDER_ID) REFERENCES POS_ORDERS(ORDER_ID);

-- 6. POS_ORDER_LINES
CREATE TABLE POS_ORDER_LINES (
    ORDER_LINE_ID NUMBER DEFAULT pos_order_lines_seq.NEXTVAL PRIMARY KEY,
    ORDER_ID NUMBER NOT NULL REFERENCES POS_ORDERS(ORDER_ID),
    LINE_NO NUMBER NOT NULL,
    ITEM_ID NUMBER NOT NULL, -- FK
    VARIANT_ID NUMBER,       -- FK
    LOT_SERIAL_ID NUMBER,    -- FK
    UOM_CODE VARCHAR2(10) NOT NULL,
    QUANTITY NUMBER(18,6) NOT NULL,
    UNIT_PRICE NUMBER(18,6) NOT NULL,
    ORIGINAL_PRICE NUMBER(18,6),
    DISCOUNT_PERCENT NUMBER(7,4) DEFAULT 0,
    DISCOUNT_AMOUNT NUMBER(18,6) DEFAULT 0,
    LINE_SUBTOTAL NUMBER(18,4),
    TAX_RATE NUMBER(7,4) DEFAULT 0,
    TAX_AMOUNT NUMBER(18,4) DEFAULT 0,
    LINE_TOTAL NUMBER(18,4),
    COST_PRICE NUMBER(18,6),
    PROMO_ID NUMBER,
    LINE_TYPE VARCHAR2(20) CHECK (LINE_TYPE IN ('REGULAR','MODIFIER','BUNDLE_HEADER','BUNDLE_COMPONENT','RETURN')),
    LINE_STATUS VARCHAR2(20) CHECK (LINE_STATUS IN ('ACTIVE','VOIDED','RETURNED')),
    LINE_NOTES VARCHAR2(500),
    KDS_STATUS VARCHAR2(20),
    SENT_TO_KDS_DATETIME TIMESTAMP,
    CREATED_BY NUMBER,
    CREATION_DATE DATE DEFAULT SYSDATE,
    LAST_UPDATED_BY NUMBER,
    LAST_UPDATE_DATE DATE,
    CONSTRAINT pos_ord_lines_uk UNIQUE (ORDER_ID, LINE_NO)
);

CREATE INDEX pos_ord_lines_item_idx ON POS_ORDER_LINES(ITEM_ID);

-- 7. POS_PAYMENT_METHODS
CREATE TABLE POS_PAYMENT_METHODS (
    PAYMENT_METHOD_ID NUMBER DEFAULT pos_payment_methods_seq.NEXTVAL PRIMARY KEY,
    METHOD_CODE VARCHAR2(30) NOT NULL UNIQUE,
    METHOD_NAME_EN VARCHAR2(100),
    METHOD_NAME_AR VARCHAR2(100),
    METHOD_TYPE VARCHAR2(20) CHECK (METHOD_TYPE IN ('CASH','CARD','CREDIT','CHEQUE','WALLET','LOYALTY','VOUCHER','BANK_TRANSFER')),
    IS_CHANGE_APPLICABLE CHAR(1) DEFAULT 'N',
    IS_OPEN_AMOUNT CHAR(1) DEFAULT 'Y',
    MAX_AMOUNT NUMBER(18,2),
    GL_ACCOUNT_CODE VARCHAR2(100),
    SORT_ORDER NUMBER,
    IS_ACTIVE CHAR(1)
);

-- 8. POS_ORDER_PAYMENTS
CREATE TABLE POS_ORDER_PAYMENTS (
    PAYMENT_ID NUMBER DEFAULT pos_order_payments_seq.NEXTVAL PRIMARY KEY,
    ORDER_ID NUMBER NOT NULL REFERENCES POS_ORDERS(ORDER_ID),
    PAYMENT_METHOD_ID NUMBER NOT NULL REFERENCES POS_PAYMENT_METHODS(PAYMENT_METHOD_ID),
    AMOUNT_TENDERED NUMBER(18,2) NOT NULL,
    AMOUNT_APPLIED NUMBER(18,2) NOT NULL,
    CHANGE_GIVEN NUMBER(18,2) DEFAULT 0,
    PAYMENT_REFERENCE VARCHAR2(100),
    CARD_LAST4 VARCHAR2(4),
    AUTHORIZATION_CODE VARCHAR2(50),
    PAYMENT_DATETIME TIMESTAMP DEFAULT SYSTIMESTAMP,
    STATUS VARCHAR2(20) CHECK (STATUS IN ('APPROVED','DECLINED','VOIDED','REFUNDED')),
    CREATED_BY NUMBER,
    CREATION_DATE DATE DEFAULT SYSDATE,
    LAST_UPDATED_BY NUMBER,
    LAST_UPDATE_DATE DATE
);

CREATE INDEX pos_ord_pay_ord_idx ON POS_ORDER_PAYMENTS(ORDER_ID);

-- END OF FILE
