-- ==============================================================================
-- FILE 3: 05_inventory_transactions.sql
-- Description: DDL for Inventory Balances, Transactions, Transfers, Cycle Counts
-- ==============================================================================

-- Sequences
CREATE SEQUENCE pos_inv_balances_seq START WITH 1 NOCACHE;
CREATE SEQUENCE pos_inv_transactions_seq START WITH 1 NOCACHE;
CREATE SEQUENCE pos_fifo_cost_layers_seq START WITH 1 NOCACHE;
CREATE SEQUENCE pos_stock_transfers_seq START WITH 1 NOCACHE;
CREATE SEQUENCE pos_stock_transf_lines_seq START WITH 1 NOCACHE;
CREATE SEQUENCE pos_cycle_count_hdrs_seq START WITH 1 NOCACHE;
CREATE SEQUENCE pos_cycle_count_lines_seq START WITH 1 NOCACHE;

-- 1. POS_INVENTORY_BALANCES
CREATE TABLE POS_INVENTORY_BALANCES (
    BALANCE_ID NUMBER DEFAULT pos_inv_balances_seq.NEXTVAL PRIMARY KEY,
    INV_ORG_ID NUMBER NOT NULL, -- FK
    SUBINV_ID NUMBER NOT NULL,  -- FK
    ITEM_ID NUMBER NOT NULL,    -- FK
    VARIANT_ID NUMBER,          -- FK nullable
    UOM_CODE VARCHAR2(10) NOT NULL, -- FK
    QUANTITY_ON_HAND NUMBER(18,6) DEFAULT 0 NOT NULL,
    QUANTITY_RESERVED NUMBER(18,6) DEFAULT 0,
    QUANTITY_IN_TRANSIT NUMBER(18,6) DEFAULT 0,
    QUANTITY_ON_ORDER NUMBER(18,6) DEFAULT 0,
    TOTAL_COST NUMBER(18,6) DEFAULT 0,
    LAST_TRANSACTION_DATE DATE,
    CREATED_BY NUMBER,
    CREATION_DATE DATE DEFAULT SYSDATE,
    LAST_UPDATED_BY NUMBER,
    LAST_UPDATE_DATE DATE,
    CONSTRAINT pos_inv_bal_uk UNIQUE (INV_ORG_ID, SUBINV_ID, ITEM_ID, VARIANT_ID, UOM_CODE)
);

CREATE INDEX pos_inv_bal_item_idx ON POS_INVENTORY_BALANCES(ITEM_ID);

-- 2. POS_INVENTORY_TRANSACTIONS
CREATE TABLE POS_INVENTORY_TRANSACTIONS (
    INV_TXN_ID NUMBER DEFAULT pos_inv_transactions_seq.NEXTVAL PRIMARY KEY,
    INV_ORG_ID NUMBER NOT NULL, -- FK
    SUBINV_ID NUMBER NOT NULL,  -- FK
    ITEM_ID NUMBER NOT NULL,    -- FK
    VARIANT_ID NUMBER,          -- FK nullable
    LOT_SERIAL_ID NUMBER,       -- FK nullable
    UOM_CODE VARCHAR2(10),      -- FK
    TXN_TYPE VARCHAR2(30) CHECK (TXN_TYPE IN ('SALE','RETURN','RECEIPT','TRANSFER_IN','TRANSFER_OUT','ADJUSTMENT','CYCLE_COUNT','WRITE_OFF','OPENING_BALANCE')),
    TXN_DATE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    QUANTITY NUMBER(18,6) NOT NULL,
    UNIT_COST NUMBER(18,6),
    TOTAL_COST NUMBER(18,6),
    REFERENCE_TYPE VARCHAR2(30),
    REFERENCE_ID NUMBER,
    ORDER_ID NUMBER,      -- FK -> POS_ORDERS
    ORDER_LINE_ID NUMBER, -- FK -> POS_ORDER_LINES
    TRANSFER_ID NUMBER,   -- FK -> POS_STOCK_TRANSFERS (created later, logical FK)
    NOTES VARCHAR2(500),
    CREATED_BY NUMBER,
    CREATION_DATE DATE DEFAULT SYSDATE,
    LAST_UPDATED_BY NUMBER,
    LAST_UPDATE_DATE DATE
);

CREATE INDEX pos_inv_txn_org_idx ON POS_INVENTORY_TRANSACTIONS(INV_ORG_ID, SUBINV_ID);
CREATE INDEX pos_inv_txn_item_idx ON POS_INVENTORY_TRANSACTIONS(ITEM_ID);
CREATE INDEX pos_inv_txn_date_idx ON POS_INVENTORY_TRANSACTIONS(TXN_DATE);

-- 3. POS_FIFO_COST_LAYERS
CREATE TABLE POS_FIFO_COST_LAYERS (
    LAYER_ID NUMBER DEFAULT pos_fifo_cost_layers_seq.NEXTVAL PRIMARY KEY,
    INV_ORG_ID NUMBER NOT NULL, -- FK
    SUBINV_ID NUMBER,           -- FK
    ITEM_ID NUMBER NOT NULL,    -- FK
    VARIANT_ID NUMBER,          -- FK nullable
    LOT_SERIAL_ID NUMBER,       -- FK nullable
    RECEIPT_DATE DATE NOT NULL,
    RECEIPT_TXN_ID NUMBER REFERENCES POS_INVENTORY_TRANSACTIONS(INV_TXN_ID),
    ORIGINAL_QUANTITY NUMBER(18,6) NOT NULL,
    REMAINING_QUANTITY NUMBER(18,6) NOT NULL,
    UNIT_COST NUMBER(18,6) NOT NULL,
    LAYER_STATUS VARCHAR2(10) CHECK (LAYER_STATUS IN ('OPEN','PARTIAL','CONSUMED')),
    CREATED_BY NUMBER,
    CREATION_DATE DATE DEFAULT SYSDATE,
    LAST_UPDATED_BY NUMBER,
    LAST_UPDATE_DATE DATE
);

CREATE INDEX pos_fifo_cost_item_idx ON POS_FIFO_COST_LAYERS(ITEM_ID);
CREATE INDEX pos_fifo_cost_status_idx ON POS_FIFO_COST_LAYERS(LAYER_STATUS);

-- 4. POS_STOCK_TRANSFERS
CREATE TABLE POS_STOCK_TRANSFERS (
    TRANSFER_ID NUMBER DEFAULT pos_stock_transfers_seq.NEXTVAL PRIMARY KEY,
    TRANSFER_NO VARCHAR2(30) NOT NULL UNIQUE,
    FROM_INV_ORG_ID NUMBER NOT NULL, -- FK
    TO_INV_ORG_ID NUMBER NOT NULL,   -- FK
    FROM_SUBINV_ID NUMBER,           -- FK
    TO_SUBINV_ID NUMBER,             -- FK
    TRANSFER_STATUS VARCHAR2(20) CHECK (TRANSFER_STATUS IN ('DRAFT','REQUESTED','APPROVED','IN_TRANSIT','RECEIVED','CANCELLED')),
    TRANSFER_DATE DATE,
    EXPECTED_DATE DATE,
    ACTUAL_RECEIVE_DATE DATE,
    NOTES VARCHAR2(1000),
    APPROVED_BY NUMBER,
    CREATED_BY NUMBER,
    CREATION_DATE DATE DEFAULT SYSDATE,
    LAST_UPDATED_BY NUMBER,
    LAST_UPDATE_DATE DATE
);

-- Note: Now we can add the FK from POS_INVENTORY_TRANSACTIONS to POS_STOCK_TRANSFERS if desired.
ALTER TABLE POS_INVENTORY_TRANSACTIONS ADD CONSTRAINT pos_inv_txn_tsfr_fk FOREIGN KEY (TRANSFER_ID) REFERENCES POS_STOCK_TRANSFERS(TRANSFER_ID);

-- 5. POS_STOCK_TRANSFER_LINES
CREATE TABLE POS_STOCK_TRANSFER_LINES (
    TRANSFER_LINE_ID NUMBER DEFAULT pos_stock_transf_lines_seq.NEXTVAL PRIMARY KEY,
    TRANSFER_ID NUMBER NOT NULL REFERENCES POS_STOCK_TRANSFERS(TRANSFER_ID),
    LINE_NO NUMBER,
    ITEM_ID NUMBER NOT NULL,  -- FK
    VARIANT_ID NUMBER,        -- FK nullable
    LOT_SERIAL_ID NUMBER,     -- FK nullable
    UOM_CODE VARCHAR2(10),    -- FK
    REQUESTED_QTY NUMBER(18,6),
    APPROVED_QTY NUMBER(18,6),
    SHIPPED_QTY NUMBER(18,6),
    RECEIVED_QTY NUMBER(18,6),
    UNIT_COST NUMBER(18,6),
    LINE_STATUS VARCHAR2(20),
    CREATED_BY NUMBER,
    CREATION_DATE DATE DEFAULT SYSDATE,
    LAST_UPDATED_BY NUMBER,
    LAST_UPDATE_DATE DATE
);

CREATE INDEX pos_stk_tsfr_ln_tsfr_idx ON POS_STOCK_TRANSFER_LINES(TRANSFER_ID);

-- 6. POS_CYCLE_COUNT_HEADERS
CREATE TABLE POS_CYCLE_COUNT_HEADERS (
    CYCLE_COUNT_ID NUMBER DEFAULT pos_cycle_count_hdrs_seq.NEXTVAL PRIMARY KEY,
    COUNT_NO VARCHAR2(30) NOT NULL UNIQUE,
    INV_ORG_ID NUMBER NOT NULL, -- FK
    SUBINV_ID NUMBER,           -- FK nullable
    COUNT_TYPE VARCHAR2(20) CHECK (COUNT_TYPE IN ('FULL','PARTIAL','ABC','SPOT')),
    STATUS VARCHAR2(20) CHECK (STATUS IN ('DRAFT','IN_PROGRESS','COMPLETED','APPROVED')),
    PLANNED_DATE DATE,
    ACTUAL_START_DATE DATE,
    ACTUAL_END_DATE DATE,
    APPROVED_BY NUMBER,
    NOTES VARCHAR2(1000),
    CREATED_BY NUMBER,
    CREATION_DATE DATE DEFAULT SYSDATE,
    LAST_UPDATED_BY NUMBER,
    LAST_UPDATE_DATE DATE
);

-- 7. POS_CYCLE_COUNT_LINES
CREATE TABLE POS_CYCLE_COUNT_LINES (
    COUNT_LINE_ID NUMBER DEFAULT pos_cycle_count_lines_seq.NEXTVAL PRIMARY KEY,
    CYCLE_COUNT_ID NUMBER NOT NULL REFERENCES POS_CYCLE_COUNT_HEADERS(CYCLE_COUNT_ID),
    ITEM_ID NUMBER NOT NULL,    -- FK
    VARIANT_ID NUMBER,          -- FK nullable
    SUBINV_ID NUMBER NOT NULL,  -- FK
    SYSTEM_QTY NUMBER(18,6),
    COUNTED_QTY NUMBER(18,6),
    VARIANCE_QTY NUMBER(18,6) GENERATED ALWAYS AS (COUNTED_QTY - SYSTEM_QTY) VIRTUAL,
    UNIT_COST NUMBER(18,6),
    VARIANCE_VALUE NUMBER(18,4) GENERATED ALWAYS AS ((COUNTED_QTY - SYSTEM_QTY) * UNIT_COST) VIRTUAL,
    STATUS VARCHAR2(20) CHECK (STATUS IN ('PENDING','COUNTED','APPROVED','ADJUSTED')),
    COUNTED_BY NUMBER,
    COUNTED_DATE DATE,
    APPROVED_BY NUMBER,
    CREATED_BY NUMBER,
    CREATION_DATE DATE DEFAULT SYSDATE,
    LAST_UPDATED_BY NUMBER,
    LAST_UPDATE_DATE DATE
);

CREATE INDEX pos_cyc_cnt_ln_hdr_idx ON POS_CYCLE_COUNT_LINES(CYCLE_COUNT_ID);
CREATE INDEX pos_cyc_cnt_ln_item_idx ON POS_CYCLE_COUNT_LINES(ITEM_ID);

-- END OF FILE
