-- ==============================================================================
-- 06_financials_gl_ar_ap.sql
-- Description: Financials (GL, AR, AP) Tables for Enterprise POS & ERP
-- Oracle 12c+ Compatible
-- ==============================================================================

-- Sequences
CREATE SEQUENCE POS_COA_SEGMENTS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE POS_COA_ACCOUNTS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE POS_GL_PERIODS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE POS_GL_JOURNALS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE POS_GL_JOURNAL_LINES_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE POS_SLA_RULES_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE POS_AR_INVOICES_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE POS_AR_RECEIPTS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE POS_AR_RECEIPT_APPS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE POS_SUPPLIERS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE POS_PURCHASE_ORDERS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE POS_PO_LINES_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE POS_AP_INVOICES_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE POS_AP_PAYMENTS_SEQ START WITH 1 INCREMENT BY 1;

-- 1. POS_COA_SEGMENTS
CREATE TABLE POS_COA_SEGMENTS (
    SEGMENT_ID NUMBER DEFAULT POS_COA_SEGMENTS_SEQ.NEXTVAL PRIMARY KEY,
    SEGMENT_NUM NUMBER(2) NOT NULL,
    SEGMENT_CODE VARCHAR2(30) NOT NULL UNIQUE,
    SEGMENT_NAME_EN VARCHAR2(100),
    SEGMENT_NAME_AR VARCHAR2(100),
    SEGMENT_TYPE VARCHAR2(20) CHECK (SEGMENT_TYPE IN ('COMPANY','COST_CENTER','ACCOUNT','PRODUCT','INTERCOMPANY','FUTURE')),
    MAX_LENGTH NUMBER(2),
    IS_REQUIRED CHAR(1),
    VALUE_SET_CODE VARCHAR2(50),
    LEGAL_ENTITY_ID NUMBER,
    SORT_ORDER NUMBER,
    IS_ACTIVE CHAR(1),
    CREATED_BY NUMBER,
    CREATION_DATE DATE DEFAULT SYSDATE,
    LAST_UPDATED_BY NUMBER,
    LAST_UPDATE_DATE DATE DEFAULT SYSDATE
);
COMMENT ON TABLE POS_COA_SEGMENTS IS 'Chart of Accounts Segment Definition';

-- 2. POS_COA_ACCOUNTS
CREATE TABLE POS_COA_ACCOUNTS (
    ACCOUNT_ID NUMBER DEFAULT POS_COA_ACCOUNTS_SEQ.NEXTVAL PRIMARY KEY,
    ACCOUNT_CODE VARCHAR2(150) NOT NULL UNIQUE,
    SEG1_VALUE VARCHAR2(30),
    SEG2_VALUE VARCHAR2(30),
    SEG3_VALUE VARCHAR2(30),
    SEG4_VALUE VARCHAR2(30),
    ACCOUNT_NAME_EN VARCHAR2(240),
    ACCOUNT_NAME_AR VARCHAR2(240),
    ACCOUNT_TYPE VARCHAR2(20) CHECK (ACCOUNT_TYPE IN ('ASSET','LIABILITY','EQUITY','REVENUE','EXPENSE','CONTRA')),
    NORMAL_BALANCE VARCHAR2(6) CHECK (NORMAL_BALANCE IN ('DEBIT','CREDIT')),
    PARENT_ACCOUNT_ID NUMBER REFERENCES POS_COA_ACCOUNTS(ACCOUNT_ID),
    ACCOUNT_LEVEL NUMBER(2),
    IS_DETAIL CHAR(1) DEFAULT 'Y',
    IS_CONTROL CHAR(1) DEFAULT 'N',
    IS_RECONCILABLE CHAR(1),
    IS_ACTIVE CHAR(1),
    LEGAL_ENTITY_ID NUMBER NOT NULL,
    CREATED_BY NUMBER,
    CREATION_DATE DATE DEFAULT SYSDATE,
    LAST_UPDATED_BY NUMBER,
    LAST_UPDATE_DATE DATE DEFAULT SYSDATE
);
COMMENT ON TABLE POS_COA_ACCOUNTS IS 'Chart of Accounts (individual account combinations)';

-- 3. POS_GL_PERIODS
CREATE TABLE POS_GL_PERIODS (
    PERIOD_ID NUMBER DEFAULT POS_GL_PERIODS_SEQ.NEXTVAL PRIMARY KEY,
    LEGAL_ENTITY_ID NUMBER NOT NULL,
    PERIOD_NAME VARCHAR2(20) NOT NULL,
    PERIOD_YEAR NUMBER(4),
    PERIOD_NUM NUMBER(2),
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
    CLOSE_STATUS VARCHAR2(20) CHECK (CLOSE_STATUS IN ('OPEN','CLOSED','PERMANENTLY_CLOSED','FUTURE')),
    CLOSED_BY NUMBER,
    CLOSED_DATE DATE,
    CREATED_BY NUMBER,
    CREATION_DATE DATE DEFAULT SYSDATE,
    LAST_UPDATED_BY NUMBER,
    LAST_UPDATE_DATE DATE DEFAULT SYSDATE,
    CONSTRAINT POS_GL_PERIODS_UK UNIQUE (LEGAL_ENTITY_ID, PERIOD_YEAR, PERIOD_NUM)
);
COMMENT ON TABLE POS_GL_PERIODS IS 'Accounting Periods (Fiscal Calendar)';

-- 4. POS_GL_JOURNALS
CREATE TABLE POS_GL_JOURNALS (
    JOURNAL_ID NUMBER DEFAULT POS_GL_JOURNALS_SEQ.NEXTVAL PRIMARY KEY,
    JOURNAL_NO VARCHAR2(30) NOT NULL UNIQUE,
    LEGAL_ENTITY_ID NUMBER NOT NULL,
    PERIOD_ID NUMBER NOT NULL REFERENCES POS_GL_PERIODS(PERIOD_ID),
    JOURNAL_DATE DATE NOT NULL,
    SOURCE VARCHAR2(30) CHECK (SOURCE IN ('POS_SALE','POS_RETURN','POS_SHIFT','INVENTORY','AP','AR','MANUAL','PAYROLL')),
    CATEGORY VARCHAR2(30),
    DESCRIPTION VARCHAR2(500),
    CURRENCY_CODE VARCHAR2(3),
    EXCHANGE_RATE NUMBER(18,8) DEFAULT 1,
    TOTAL_DEBIT NUMBER(18,4),
    TOTAL_CREDIT NUMBER(18,4),
    STATUS VARCHAR2(20) CHECK (STATUS IN ('DRAFT','POSTED','REVERSED','ERROR')),
    REFERENCE_TYPE VARCHAR2(30),
    REFERENCE_ID NUMBER,
    POSTED_BY NUMBER,
    POSTED_DATE DATE,
    REVERSAL_JOURNAL_ID NUMBER REFERENCES POS_GL_JOURNALS(JOURNAL_ID),
    CREATED_BY NUMBER,
    CREATION_DATE DATE DEFAULT SYSDATE,
    LAST_UPDATED_BY NUMBER,
    LAST_UPDATE_DATE DATE DEFAULT SYSDATE
);
COMMENT ON TABLE POS_GL_JOURNALS IS 'General Ledger Journal Headers';

-- 5. POS_GL_JOURNAL_LINES
CREATE TABLE POS_GL_JOURNAL_LINES (
    JOURNAL_LINE_ID NUMBER DEFAULT POS_GL_JOURNAL_LINES_SEQ.NEXTVAL PRIMARY KEY,
    JOURNAL_ID NUMBER NOT NULL REFERENCES POS_GL_JOURNALS(JOURNAL_ID),
    LINE_NO NUMBER NOT NULL,
    ACCOUNT_ID NUMBER NOT NULL REFERENCES POS_COA_ACCOUNTS(ACCOUNT_ID),
    DEBIT_AMOUNT NUMBER(18,4) DEFAULT 0,
    CREDIT_AMOUNT NUMBER(18,4) DEFAULT 0,
    FUNCTIONAL_DEBIT NUMBER(18,4),
    FUNCTIONAL_CREDIT NUMBER(18,4),
    DESCRIPTION VARCHAR2(500),
    INV_ORG_ID NUMBER,
    REFERENCE1 VARCHAR2(150),
    REFERENCE2 VARCHAR2(150),
    CREATED_BY NUMBER,
    CREATION_DATE DATE DEFAULT SYSDATE,
    LAST_UPDATED_BY NUMBER,
    LAST_UPDATE_DATE DATE DEFAULT SYSDATE,
    CONSTRAINT POS_GL_JNL_LINES_UK UNIQUE (JOURNAL_ID, LINE_NO)
);
COMMENT ON TABLE POS_GL_JOURNAL_LINES IS 'GL Journal Distribution Lines';

-- 6. POS_SLA_RULES
CREATE TABLE POS_SLA_RULES (
    RULE_ID NUMBER DEFAULT POS_SLA_RULES_SEQ.NEXTVAL PRIMARY KEY,
    RULE_CODE VARCHAR2(50) NOT NULL UNIQUE,
    RULE_NAME VARCHAR2(240),
    SOURCE VARCHAR2(30),
    TXN_TYPE VARCHAR2(30),
    LINE_TYPE VARCHAR2(30),
    DEBIT_ACCOUNT_ID NUMBER REFERENCES POS_COA_ACCOUNTS(ACCOUNT_ID),
    CREDIT_ACCOUNT_ID NUMBER REFERENCES POS_COA_ACCOUNTS(ACCOUNT_ID),
    AMOUNT_TYPE VARCHAR2(30) CHECK (AMOUNT_TYPE IN ('SUBTOTAL','TAX','DISCOUNT','COST','TOTAL','ROUNDING')),
    IS_ACTIVE CHAR(1),
    PRIORITY NUMBER,
    CREATED_BY NUMBER,
    CREATION_DATE DATE DEFAULT SYSDATE,
    LAST_UPDATED_BY NUMBER,
    LAST_UPDATE_DATE DATE DEFAULT SYSDATE
);
COMMENT ON TABLE POS_SLA_RULES IS 'Subledger Accounting Rules';

-- 7. POS_AR_CUSTOMERS is skipped (use POS_CUSTOMERS master)

-- 8. POS_AR_INVOICES
CREATE TABLE POS_AR_INVOICES (
    AR_INVOICE_ID NUMBER DEFAULT POS_AR_INVOICES_SEQ.NEXTVAL PRIMARY KEY,
    INVOICE_NO VARCHAR2(30) NOT NULL UNIQUE,
    CUSTOMER_ID NUMBER NOT NULL,
    INV_ORG_ID NUMBER NOT NULL,
    LEGAL_ENTITY_ID NUMBER NOT NULL,
    PERIOD_ID NUMBER,
    INVOICE_DATE DATE NOT NULL,
    DUE_DATE DATE,
    INVOICE_TYPE VARCHAR2(20) CHECK (INVOICE_TYPE IN ('STANDARD','CREDIT_MEMO','DEBIT_MEMO','RECEIPT_ADVANCE')),
    ORDER_ID NUMBER,
    CURRENCY_CODE VARCHAR2(3),
    EXCHANGE_RATE NUMBER(18,8),
    INVOICE_AMOUNT NUMBER(18,2),
    TAX_AMOUNT NUMBER(18,2),
    TOTAL_AMOUNT NUMBER(18,2),
    AMOUNT_APPLIED NUMBER(18,2) DEFAULT 0,
    AMOUNT_DUE NUMBER(18,2),
    STATUS VARCHAR2(20) CHECK (STATUS IN ('DRAFT','APPROVED','POSTED','PARTIALLY_PAID','PAID','CANCELLED')),
    PAYMENT_TERMS VARCHAR2(20),
    NOTES VARCHAR2(1000),
    E_INVOICE_UUID VARCHAR2(100),
    E_INVOICE_STATUS VARCHAR2(20),
    E_INVOICE_QR CLOB,
    CREATED_BY NUMBER,
    CREATION_DATE DATE DEFAULT SYSDATE,
    LAST_UPDATED_BY NUMBER,
    LAST_UPDATE_DATE DATE DEFAULT SYSDATE
);
COMMENT ON TABLE POS_AR_INVOICES IS 'Accounts Receivable Invoice Header';

-- 9. POS_AR_RECEIPTS
CREATE TABLE POS_AR_RECEIPTS (
    RECEIPT_ID NUMBER DEFAULT POS_AR_RECEIPTS_SEQ.NEXTVAL PRIMARY KEY,
    RECEIPT_NO VARCHAR2(30) NOT NULL UNIQUE,
    CUSTOMER_ID NUMBER NOT NULL,
    INV_ORG_ID NUMBER NOT NULL,
    RECEIPT_DATE DATE,
    PAYMENT_METHOD_ID NUMBER,
    AMOUNT NUMBER(18,2),
    APPLIED_AMOUNT NUMBER(18,2) DEFAULT 0,
    UNAPPLIED_AMOUNT NUMBER(18,2),
    CURRENCY_CODE VARCHAR2(3),
    STATUS VARCHAR2(20) CHECK (STATUS IN ('CONFIRMED','APPLIED','UNAPPLIED','REVERSED')),
    REFERENCE VARCHAR2(100),
    JOURNAL_ID NUMBER,
    CREATED_BY NUMBER,
    CREATION_DATE DATE DEFAULT SYSDATE,
    LAST_UPDATED_BY NUMBER,
    LAST_UPDATE_DATE DATE DEFAULT SYSDATE
);
COMMENT ON TABLE POS_AR_RECEIPTS IS 'AR Cash Receipts';

-- 10. POS_AR_RECEIPT_APPLICATIONS
CREATE TABLE POS_AR_RECEIPT_APPLICATIONS (
    APPLICATION_ID NUMBER DEFAULT POS_AR_RECEIPT_APPS_SEQ.NEXTVAL PRIMARY KEY,
    RECEIPT_ID NUMBER NOT NULL REFERENCES POS_AR_RECEIPTS(RECEIPT_ID),
    AR_INVOICE_ID NUMBER NOT NULL REFERENCES POS_AR_INVOICES(AR_INVOICE_ID),
    APPLIED_AMOUNT NUMBER(18,2) NOT NULL,
    APPLICATION_DATE DATE,
    CREATED_BY NUMBER,
    CREATION_DATE DATE DEFAULT SYSDATE,
    LAST_UPDATED_BY NUMBER,
    LAST_UPDATE_DATE DATE DEFAULT SYSDATE
);
COMMENT ON TABLE POS_AR_RECEIPT_APPLICATIONS IS 'Receipt-to-Invoice Applications';

-- 11. POS_SUPPLIERS
CREATE TABLE POS_SUPPLIERS (
    SUPPLIER_ID NUMBER DEFAULT POS_SUPPLIERS_SEQ.NEXTVAL PRIMARY KEY,
    SUPPLIER_CODE VARCHAR2(50) NOT NULL UNIQUE,
    SUPPLIER_NAME_EN VARCHAR2(240) NOT NULL,
    SUPPLIER_NAME_AR VARCHAR2(240),
    SUPPLIER_TYPE VARCHAR2(20) CHECK (SUPPLIER_TYPE IN ('GOODS','SERVICE','BOTH')),
    TAX_REGISTRATION_NO VARCHAR2(50),
    PAYMENT_TERMS VARCHAR2(20),
    CREDIT_DAYS NUMBER DEFAULT 30,
    CURRENCY_CODE VARCHAR2(3),
    BANK_NAME VARCHAR2(100),
    BANK_ACCOUNT_NO VARCHAR2(50),
    IBAN VARCHAR2(50),
    CONTACT_NAME VARCHAR2(150),
    EMAIL VARCHAR2(240),
    PHONE VARCHAR2(50),
    ADDRESS_LINE1 VARCHAR2(240),
    ADDRESS_LINE2 VARCHAR2(240),
    COUNTRY_CODE VARCHAR2(5),
    IS_ACTIVE CHAR(1),
    CREATED_BY NUMBER,
    CREATION_DATE DATE DEFAULT SYSDATE,
    LAST_UPDATED_BY NUMBER,
    LAST_UPDATE_DATE DATE DEFAULT SYSDATE
);
COMMENT ON TABLE POS_SUPPLIERS IS 'Supplier/Vendor Master';

-- 12. POS_PURCHASE_ORDERS
CREATE TABLE POS_PURCHASE_ORDERS (
    PO_ID NUMBER DEFAULT POS_PURCHASE_ORDERS_SEQ.NEXTVAL PRIMARY KEY,
    PO_NO VARCHAR2(30) NOT NULL UNIQUE,
    SUPPLIER_ID NUMBER NOT NULL REFERENCES POS_SUPPLIERS(SUPPLIER_ID),
    INV_ORG_ID NUMBER NOT NULL,
    PO_DATE DATE NOT NULL,
    EXPECTED_DATE DATE,
    PO_STATUS VARCHAR2(20) CHECK (PO_STATUS IN ('DRAFT','SUBMITTED','APPROVED','PARTIALLY_RECEIVED','FULLY_RECEIVED','CANCELLED')),
    CURRENCY_CODE VARCHAR2(3),
    EXCHANGE_RATE NUMBER(18,8) DEFAULT 1,
    SUBTOTAL NUMBER(18,2),
    TAX_AMOUNT NUMBER(18,2),
    TOTAL_AMOUNT NUMBER(18,2),
    APPROVED_BY NUMBER,
    APPROVED_DATE DATE,
    NOTES VARCHAR2(1000),
    CREATED_BY NUMBER,
    CREATION_DATE DATE DEFAULT SYSDATE,
    LAST_UPDATED_BY NUMBER,
    LAST_UPDATE_DATE DATE DEFAULT SYSDATE
);
COMMENT ON TABLE POS_PURCHASE_ORDERS IS 'Purchase Order Header';

-- 13. POS_PO_LINES
CREATE TABLE POS_PO_LINES (
    PO_LINE_ID NUMBER DEFAULT POS_PO_LINES_SEQ.NEXTVAL PRIMARY KEY,
    PO_ID NUMBER NOT NULL REFERENCES POS_PURCHASE_ORDERS(PO_ID),
    LINE_NO NUMBER,
    ITEM_ID NUMBER NOT NULL,
    VARIANT_ID NUMBER,
    UOM_CODE VARCHAR2(30),
    ORDERED_QTY NUMBER(18,6),
    RECEIVED_QTY NUMBER(18,6) DEFAULT 0,
    UNIT_PRICE NUMBER(18,6),
    LINE_AMOUNT NUMBER(18,4),
    TAX_RATE NUMBER(7,4),
    TAX_AMOUNT NUMBER(18,4),
    LINE_TOTAL NUMBER(18,4),
    STATUS VARCHAR2(20) CHECK (STATUS IN ('OPEN','PARTIALLY_RECEIVED','FULLY_RECEIVED','CANCELLED')),
    CREATED_BY NUMBER,
    CREATION_DATE DATE DEFAULT SYSDATE,
    LAST_UPDATED_BY NUMBER,
    LAST_UPDATE_DATE DATE DEFAULT SYSDATE,
    CONSTRAINT POS_PO_LINES_UK UNIQUE (PO_ID, LINE_NO)
);
COMMENT ON TABLE POS_PO_LINES IS 'Purchase Order Lines';

-- 14. POS_AP_INVOICES
CREATE TABLE POS_AP_INVOICES (
    AP_INVOICE_ID NUMBER DEFAULT POS_AP_INVOICES_SEQ.NEXTVAL PRIMARY KEY,
    INVOICE_NO VARCHAR2(30) NOT NULL,
    SUPPLIER_ID NUMBER NOT NULL REFERENCES POS_SUPPLIERS(SUPPLIER_ID),
    INV_ORG_ID NUMBER NOT NULL,
    PO_ID NUMBER REFERENCES POS_PURCHASE_ORDERS(PO_ID),
    INVOICE_DATE DATE,
    DUE_DATE DATE,
    INVOICE_AMOUNT NUMBER(18,2),
    TAX_AMOUNT NUMBER(18,2),
    TOTAL_AMOUNT NUMBER(18,2),
    AMOUNT_PAID NUMBER(18,2) DEFAULT 0,
    STATUS VARCHAR2(20) CHECK (STATUS IN ('DRAFT','MATCHING','APPROVED','POSTED','PARTIALLY_PAID','PAID','ON_HOLD','CANCELLED')),
    HOLD_REASON VARCHAR2(500),
    THREE_WAY_MATCH_STATUS VARCHAR2(20) CHECK (THREE_WAY_MATCH_STATUS IN ('PENDING','MATCHED','EXCEPTION','WAIVED')),
    JOURNAL_ID NUMBER,
    NOTES VARCHAR2(1000),
    CREATED_BY NUMBER,
    CREATION_DATE DATE DEFAULT SYSDATE,
    LAST_UPDATED_BY NUMBER,
    LAST_UPDATE_DATE DATE DEFAULT SYSDATE,
    CONSTRAINT POS_AP_INVOICES_UK UNIQUE (SUPPLIER_ID, INVOICE_NO)
);
COMMENT ON TABLE POS_AP_INVOICES IS 'Accounts Payable Invoice Header';

-- 15. POS_AP_PAYMENTS
CREATE TABLE POS_AP_PAYMENTS (
    AP_PAYMENT_ID NUMBER DEFAULT POS_AP_PAYMENTS_SEQ.NEXTVAL PRIMARY KEY,
    PAYMENT_NO VARCHAR2(30) NOT NULL UNIQUE,
    SUPPLIER_ID NUMBER NOT NULL REFERENCES POS_SUPPLIERS(SUPPLIER_ID),
    AP_INVOICE_ID NUMBER NOT NULL REFERENCES POS_AP_INVOICES(AP_INVOICE_ID),
    INV_ORG_ID NUMBER NOT NULL,
    PAYMENT_DATE DATE,
    PAYMENT_METHOD VARCHAR2(30),
    AMOUNT NUMBER(18,2),
    REFERENCE VARCHAR2(100),
    STATUS VARCHAR2(20) CHECK (STATUS IN ('PENDING','CLEARED','VOIDED')),
    JOURNAL_ID NUMBER,
    CREATED_BY NUMBER,
    CREATION_DATE DATE DEFAULT SYSDATE,
    LAST_UPDATED_BY NUMBER,
    LAST_UPDATE_DATE DATE DEFAULT SYSDATE
);
COMMENT ON TABLE POS_AP_PAYMENTS IS 'AP Vendor Payments';
