-- ==============================================================================
-- 07_tax_engine.sql
-- Description: Tax Engine Tables for Enterprise POS & ERP
-- Oracle 12c+ Compatible
-- ==============================================================================

-- Sequences
CREATE SEQUENCE POS_TAX_REGIMES_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE POS_TAX_TYPES_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE POS_TAX_RATES_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE POS_TAX_RULES_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE POS_TAX_EXEMPTIONS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE POS_ORDER_TAX_LINES_SEQ START WITH 1 INCREMENT BY 1;

-- 1. POS_TAX_REGIMES
CREATE TABLE POS_TAX_REGIMES (
    REGIME_ID NUMBER DEFAULT POS_TAX_REGIMES_SEQ.NEXTVAL PRIMARY KEY,
    REGIME_CODE VARCHAR2(30) NOT NULL UNIQUE,
    REGIME_NAME VARCHAR2(240),
    COUNTRY_CODE VARCHAR2(5),
    TAX_AUTHORITY VARCHAR2(240),
    IS_ACTIVE CHAR(1),
    CREATED_BY NUMBER,
    CREATION_DATE DATE DEFAULT SYSDATE,
    LAST_UPDATED_BY NUMBER,
    LAST_UPDATE_DATE DATE DEFAULT SYSDATE
);
COMMENT ON TABLE POS_TAX_REGIMES IS 'Tax Regime (e.g., VAT_SA, GST_IN)';

-- 2. POS_TAX_TYPES
CREATE TABLE POS_TAX_TYPES (
    TAX_TYPE_ID NUMBER DEFAULT POS_TAX_TYPES_SEQ.NEXTVAL PRIMARY KEY,
    REGIME_ID NUMBER NOT NULL REFERENCES POS_TAX_REGIMES(REGIME_ID),
    TAX_CODE VARCHAR2(30) NOT NULL UNIQUE,
    TAX_NAME_EN VARCHAR2(100),
    TAX_NAME_AR VARCHAR2(100),
    TAX_CLASS VARCHAR2(20) CHECK (TAX_CLASS IN ('VAT','GST','EXCISE','WITHHOLDING','COMPOUND','STAMP')),
    COMPOUND_ON VARCHAR2(30),
    IS_RECOVERABLE CHAR(1),
    IS_ACTIVE CHAR(1),
    CREATED_BY NUMBER,
    CREATION_DATE DATE DEFAULT SYSDATE,
    LAST_UPDATED_BY NUMBER,
    LAST_UPDATE_DATE DATE DEFAULT SYSDATE
);
COMMENT ON TABLE POS_TAX_TYPES IS 'Tax Types within a Regime';

-- 3. POS_TAX_RATES
CREATE TABLE POS_TAX_RATES (
    TAX_RATE_ID NUMBER DEFAULT POS_TAX_RATES_SEQ.NEXTVAL PRIMARY KEY,
    TAX_TYPE_ID NUMBER NOT NULL REFERENCES POS_TAX_TYPES(TAX_TYPE_ID),
    RATE_CODE VARCHAR2(30) NOT NULL,
    RATE_PERCENT NUMBER(7,4) NOT NULL,
    EFFECTIVE_FROM DATE NOT NULL,
    EFFECTIVE_TO DATE,
    IS_ZERO_RATED CHAR(1) DEFAULT 'N',
    IS_EXEMPT CHAR(1) DEFAULT 'N',
    IS_ACTIVE CHAR(1),
    CREATED_BY NUMBER,
    CREATION_DATE DATE DEFAULT SYSDATE,
    LAST_UPDATED_BY NUMBER,
    LAST_UPDATE_DATE DATE DEFAULT SYSDATE,
    CONSTRAINT POS_TAX_RATES_UK UNIQUE (TAX_TYPE_ID, RATE_CODE, EFFECTIVE_FROM)
);
COMMENT ON TABLE POS_TAX_RATES IS 'Tax Rates with effective date ranges';

-- 4. POS_TAX_RULES
CREATE TABLE POS_TAX_RULES (
    RULE_ID NUMBER DEFAULT POS_TAX_RULES_SEQ.NEXTVAL PRIMARY KEY,
    TAX_RATE_ID NUMBER NOT NULL REFERENCES POS_TAX_RATES(TAX_RATE_ID),
    RULE_NAME VARCHAR2(240),
    PRIORITY NUMBER(3) NOT NULL,
    LEGAL_ENTITY_ID NUMBER,
    INV_ORG_ID NUMBER,
    CATEGORY_ID NUMBER,
    ITEM_ID NUMBER,
    CUSTOMER_TYPE VARCHAR2(20),
    CUSTOMER_ID NUMBER,
    IS_EXEMPT CHAR(1) DEFAULT 'N',
    EXEMPT_REASON VARCHAR2(240),
    IS_ACTIVE CHAR(1),
    CREATED_BY NUMBER,
    CREATION_DATE DATE DEFAULT SYSDATE,
    LAST_UPDATED_BY NUMBER,
    LAST_UPDATE_DATE DATE DEFAULT SYSDATE
);
COMMENT ON TABLE POS_TAX_RULES IS 'Rule-based Tax Determination Matrix';

-- 5. POS_TAX_EXEMPTIONS
CREATE TABLE POS_TAX_EXEMPTIONS (
    EXEMPTION_ID NUMBER DEFAULT POS_TAX_EXEMPTIONS_SEQ.NEXTVAL PRIMARY KEY,
    EXEMPTION_NO VARCHAR2(50) NOT NULL UNIQUE,
    CUSTOMER_ID NUMBER,
    ITEM_ID NUMBER,
    CATEGORY_ID NUMBER,
    TAX_TYPE_ID NUMBER NOT NULL REFERENCES POS_TAX_TYPES(TAX_TYPE_ID),
    EXEMPTION_PERCENT NUMBER(5,2) DEFAULT 100,
    VALID_FROM DATE,
    VALID_TO DATE,
    EXEMPTION_REASON VARCHAR2(500),
    IS_ACTIVE CHAR(1),
    CREATED_BY NUMBER,
    CREATION_DATE DATE DEFAULT SYSDATE,
    LAST_UPDATED_BY NUMBER,
    LAST_UPDATE_DATE DATE DEFAULT SYSDATE
);
COMMENT ON TABLE POS_TAX_EXEMPTIONS IS 'Customer/Item specific tax exemptions';

-- 6. POS_ORDER_TAX_LINES
CREATE TABLE POS_ORDER_TAX_LINES (
    ORDER_TAX_ID NUMBER DEFAULT POS_ORDER_TAX_LINES_SEQ.NEXTVAL PRIMARY KEY,
    ORDER_ID NUMBER NOT NULL,
    ORDER_LINE_ID NUMBER NOT NULL,
    TAX_RATE_ID NUMBER NOT NULL REFERENCES POS_TAX_RATES(TAX_RATE_ID),
    TAXABLE_AMOUNT NUMBER(18,4),
    TAX_PERCENT NUMBER(7,4),
    TAX_AMOUNT NUMBER(18,4),
    IS_INCLUSIVE CHAR(1) DEFAULT 'N',
    IS_RECOVERABLE CHAR(1) DEFAULT 'Y',
    CREATED_BY NUMBER,
    CREATION_DATE DATE DEFAULT SYSDATE,
    LAST_UPDATED_BY NUMBER,
    LAST_UPDATE_DATE DATE DEFAULT SYSDATE
);
COMMENT ON TABLE POS_ORDER_TAX_LINES IS 'Tax distribution per order line (detailed tax ledger)';
