-- ==============================================================================
-- 08_offline_sync_and_audit.sql
-- Description: Offline Sync, Audit, Settings & Templates for POS & ERP
-- Oracle 12c+ Compatible
-- ==============================================================================

-- Sequences
CREATE SEQUENCE POS_OFFLINE_SYNC_QUEUE_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE POS_SYNC_CONFLICT_LOG_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE POS_AUDIT_LOG_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE POS_APP_SETTINGS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE POS_PRINT_TEMPLATES_SEQ START WITH 1 INCREMENT BY 1;

-- 1. POS_OFFLINE_SYNC_QUEUE
CREATE TABLE POS_OFFLINE_SYNC_QUEUE (
    SYNC_ID NUMBER DEFAULT POS_OFFLINE_SYNC_QUEUE_SEQ.NEXTVAL PRIMARY KEY,
    IDEMPOTENCY_KEY VARCHAR2(100) NOT NULL UNIQUE,
    TERMINAL_ID NUMBER,
    INV_ORG_ID NUMBER,
    CASHIER_USER_ID NUMBER,
    PAYLOAD_TYPE VARCHAR2(30) CHECK (PAYLOAD_TYPE IN ('ORDER','SHIFT_OPEN','SHIFT_CLOSE','CASH_MOVEMENT','INVENTORY_COUNT')),
    PAYLOAD CLOB NOT NULL,
    PAYLOAD_CHECKSUM VARCHAR2(64),
    CLIENT_TIMESTAMP TIMESTAMP,
    SERVER_RECEIVED_TIMESTAMP TIMESTAMP DEFAULT SYSTIMESTAMP,
    SYNC_STATUS VARCHAR2(20) DEFAULT 'PENDING' CHECK (SYNC_STATUS IN ('PENDING','PROCESSING','COMPLETED','FAILED','DUPLICATE')),
    PROCESSED_ORDER_ID NUMBER,
    RETRY_COUNT NUMBER DEFAULT 0,
    LAST_ERROR CLOB,
    PROCESSED_TIMESTAMP TIMESTAMP,
    CREATED_BY NUMBER,
    CREATION_DATE DATE DEFAULT SYSDATE,
    LAST_UPDATED_BY NUMBER,
    LAST_UPDATE_DATE DATE DEFAULT SYSDATE,
    CONSTRAINT POS_SYNC_PAYLOAD_JSON CHECK (PAYLOAD IS JSON)
);
COMMENT ON TABLE POS_OFFLINE_SYNC_QUEUE IS 'Offline transaction queue (captured in IndexedDB, synced here)';

-- 2. POS_SYNC_CONFLICT_LOG
CREATE TABLE POS_SYNC_CONFLICT_LOG (
    CONFLICT_ID NUMBER DEFAULT POS_SYNC_CONFLICT_LOG_SEQ.NEXTVAL PRIMARY KEY,
    SYNC_ID NUMBER NOT NULL REFERENCES POS_OFFLINE_SYNC_QUEUE(SYNC_ID),
    CONFLICT_TYPE VARCHAR2(50) CHECK (CONFLICT_TYPE IN ('DUPLICATE_ORDER','PRICE_MISMATCH','STOCK_SHORTAGE','INVALID_SHIFT','TIMESTAMP_GAP')),
    CONFLICT_DETAIL CLOB,
    SERVER_VALUE CLOB,
    CLIENT_VALUE CLOB,
    RESOLUTION VARCHAR2(30) CHECK (RESOLUTION IN ('CLIENT_WINS','SERVER_WINS','MANUAL','MERGED')),
    RESOLVED_BY NUMBER,
    RESOLVED_DATE DATE,
    CREATED_BY NUMBER,
    CREATION_DATE DATE DEFAULT SYSDATE,
    LAST_UPDATED_BY NUMBER,
    LAST_UPDATE_DATE DATE DEFAULT SYSDATE
);
COMMENT ON TABLE POS_SYNC_CONFLICT_LOG IS 'Conflicts detected during sync';

-- 3. POS_AUDIT_LOG
CREATE TABLE POS_AUDIT_LOG (
    AUDIT_ID NUMBER DEFAULT POS_AUDIT_LOG_SEQ.NEXTVAL PRIMARY KEY,
    TABLE_NAME VARCHAR2(100),
    RECORD_ID NUMBER,
    ACTION_TYPE VARCHAR2(10) CHECK (ACTION_TYPE IN ('INSERT','UPDATE','DELETE')),
    OLD_VALUES CLOB,
    NEW_VALUES CLOB,
    CHANGED_BY NUMBER,
    CHANGE_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    SESSION_ID VARCHAR2(100),
    IP_ADDRESS VARCHAR2(45),
    TERMINAL_ID NUMBER,
    INV_ORG_ID NUMBER,
    CONSTRAINT POS_AUDIT_OLD_JSON CHECK (OLD_VALUES IS JSON),
    CONSTRAINT POS_AUDIT_NEW_JSON CHECK (NEW_VALUES IS JSON)
);
COMMENT ON TABLE POS_AUDIT_LOG IS 'System-wide audit trail (all DML on sensitive tables)';

-- 4. POS_APP_SETTINGS
CREATE TABLE POS_APP_SETTINGS (
    SETTING_ID NUMBER DEFAULT POS_APP_SETTINGS_SEQ.NEXTVAL PRIMARY KEY,
    SETTING_SCOPE VARCHAR2(20) CHECK (SETTING_SCOPE IN ('GLOBAL','LEGAL_ENTITY','ORG','TERMINAL')),
    SCOPE_ID NUMBER,
    SETTING_KEY VARCHAR2(100) NOT NULL,
    SETTING_VALUE VARCHAR2(4000),
    SETTING_VALUE_CLOB CLOB,
    DATA_TYPE VARCHAR2(20) CHECK (DATA_TYPE IN ('STRING','NUMBER','BOOLEAN','DATE','JSON')),
    DESCRIPTION VARCHAR2(500),
    IS_ENCRYPTED CHAR(1) DEFAULT 'N',
    IS_ACTIVE CHAR(1) DEFAULT 'Y',
    CREATED_BY NUMBER,
    CREATION_DATE DATE DEFAULT SYSDATE,
    LAST_UPDATED_BY NUMBER,
    LAST_UPDATE_DATE DATE DEFAULT SYSDATE,
    CONSTRAINT POS_APP_SETTINGS_UK UNIQUE (SETTING_SCOPE, SCOPE_ID, SETTING_KEY)
);
COMMENT ON TABLE POS_APP_SETTINGS IS 'Application Configuration Key-Value Store';

-- 5. POS_PRINT_TEMPLATES
CREATE TABLE POS_PRINT_TEMPLATES (
    TEMPLATE_ID NUMBER DEFAULT POS_PRINT_TEMPLATES_SEQ.NEXTVAL PRIMARY KEY,
    TEMPLATE_CODE VARCHAR2(50) NOT NULL UNIQUE,
    TEMPLATE_TYPE VARCHAR2(30) CHECK (TEMPLATE_TYPE IN ('RECEIPT','INVOICE','KDS_TICKET','SHIFT_REPORT','PRICE_LABEL','DELIVERY_NOTE')),
    INV_ORG_ID NUMBER,
    TEMPLATE_BODY CLOB NOT NULL,
    PAPER_WIDTH NUMBER DEFAULT 80,
    IS_DEFAULT CHAR(1) DEFAULT 'N',
    IS_ACTIVE CHAR(1),
    CREATED_BY NUMBER,
    CREATION_DATE DATE DEFAULT SYSDATE,
    LAST_UPDATED_BY NUMBER,
    LAST_UPDATE_DATE DATE DEFAULT SYSDATE
);
COMMENT ON TABLE POS_PRINT_TEMPLATES IS 'Receipt and report print templates';
