-- ==============================================================================
-- 09_seed_data.sql
-- Description: Realistic Seed Data for Enterprise POS & ERP on OCI APEX
-- Compatible: Oracle 19c / 21c / 23c / Autonomous Database (OCI)
-- ==============================================================================

SET DEFINE OFF;

-- 1. LEGAL ENTITY (الكيان القانوني)
INSERT INTO POS_LEGAL_ENTITIES (
    LEGAL_ENTITY_ID, LEGAL_ENTITY_CODE, LEGAL_ENTITY_NAME, COUNTRY_CODE,
    TAX_REGISTRATION_NO, CURRENCY_CODE, FISCAL_YEAR_START_MONTH, IS_ACTIVE
) VALUES (
    1000001, 'CORP_SA', 'Saudi Enterprise Retail Group LLC', 'SA',
    '310123456700003', 'SAR', 1, 'Y'
);

-- 2. OPERATING UNIT (وحدة التشغيل)
INSERT INTO POS_OPERATING_UNITS (
    ORG_UNIT_ID, ORG_UNIT_CODE, ORG_UNIT_NAME, LEGAL_ENTITY_ID,
    ORG_TYPE, DEFAULT_CURRENCY_CODE, REPORTING_CURRENCY_CODE, IS_ACTIVE
) VALUES (
    1000001, 'OU_RIYADH_HQ', 'Riyadh Regional Operations HQ', 1000001,
    'HQ', 'SAR', 'SAR', 'Y'
);

-- 3. INVENTORY ORGANIZATIONS (الفروع والمستودعات)
INSERT INTO POS_INVENTORY_ORGS (
    INV_ORG_ID, INV_ORG_CODE, INV_ORG_NAME, ORG_UNIT_ID,
    ORG_CATEGORY, SECTOR_TYPE, CITY, COUNTRY_CODE, COSTING_METHOD, IS_ACTIVE
) VALUES (
    1000001, 'BR_OLAYA_STORE', 'Olaya Flagship Retail Store', 1000001,
    'STORE', 'HYBRID', 'Riyadh', 'SA', 'FIFO', 'Y'
);

INSERT INTO POS_INVENTORY_ORGS (
    INV_ORG_ID, INV_ORG_CODE, INV_ORG_NAME, ORG_UNIT_ID,
    ORG_CATEGORY, SECTOR_TYPE, CITY, COUNTRY_CODE, COSTING_METHOD, IS_ACTIVE
) VALUES (
    1000002, 'WH_CENTRAL', 'Central Distribution Warehouse', 1000001,
    'WAREHOUSE', 'RETAIL', 'Riyadh', 'SA', 'AVERAGE', 'Y'
);

-- 4. SUBINVENTORIES (المخازن الداخلية)
INSERT INTO POS_SUBINVENTORIES (
    SUBINV_ID, SUBINV_CODE, SUBINV_NAME, INV_ORG_ID,
    SUBINV_TYPE, IS_RESERVABLE, IS_ASSET_VALUED, IS_ACTIVE
) VALUES (
    1000001, 'MAIN_SHELF', 'Main Showroom Floor', 1000001,
    'SHELF', 'Y', 'Y', 'Y'
);

INSERT INTO POS_SUBINVENTORIES (
    SUBINV_ID, SUBINV_CODE, SUBINV_NAME, INV_ORG_ID,
    SUBINV_TYPE, IS_RESERVABLE, IS_ASSET_VALUED, IS_ACTIVE
) VALUES (
    1000002, 'BACK_STORE', 'Branch Back Storage', 1000001,
    'BACKSTORE', 'Y', 'Y', 'Y'
);

-- 5. POS TERMINALS (أجهزة الكاشير)
INSERT INTO POS_POS_TERMINALS (
    TERMINAL_ID, TERMINAL_CODE, TERMINAL_NAME, INV_ORG_ID,
    SUBINV_ID, TERMINAL_TYPE, PRINTER_IP, CASH_DRAWER_ENABLED, IS_ACTIVE
) VALUES (
    1000001, 'TERM_POS_01', 'Counter 1 Express Checkout', 1000001,
    1000001, 'CASHIER', '192.168.1.201', 'Y', 'Y'
);

INSERT INTO POS_POS_TERMINALS (
    TERMINAL_ID, TERMINAL_CODE, TERMINAL_NAME, INV_ORG_ID,
    SUBINV_ID, TERMINAL_TYPE, PRINTER_IP, CASH_DRAWER_ENABLED, IS_ACTIVE
) VALUES (
    1000002, 'TERM_POS_02', 'Counter 2 Main Cashier', 1000001,
    1000001, 'CASHIER', '192.168.1.202', 'Y', 'Y'
);

-- 6. APP USERS (المستخدمين)
INSERT INTO POS_APP_USERS (
    APP_USER_ID, APEX_USERNAME, FULL_NAME_AR, FULL_NAME_EN,
    USER_ROLE, DEFAULT_INV_ORG_ID, DEFAULT_TERMINAL_ID, IS_ACTIVE
) VALUES (
    1000001, 'ADMIN', 'مدير النظام', 'System Administrator',
    'SYSADMIN', 1000001, 1000001, 'Y'
);

INSERT INTO POS_APP_USERS (
    APP_USER_ID, APEX_USERNAME, FULL_NAME_AR, FULL_NAME_EN,
    USER_ROLE, DEFAULT_INV_ORG_ID, DEFAULT_TERMINAL_ID, IS_ACTIVE
) VALUES (
    1000002, 'CASHIER1', 'أحمد المحمد', 'Ahmed Al-Mohammed',
    'CASHIER', 1000001, 1000001, 'Y'
);

-- USER ORG ACCESS
INSERT INTO POS_USER_ORG_ACCESS (ACCESS_ID, APP_USER_ID, INV_ORG_ID, ACCESS_LEVEL)
VALUES (1000001, 1000001, 1000001, 'FULL');
INSERT INTO POS_USER_ORG_ACCESS (ACCESS_ID, APP_USER_ID, INV_ORG_ID, ACCESS_LEVEL)
VALUES (1000002, 1000001, 1000002, 'FULL');
INSERT INTO POS_USER_ORG_ACCESS (ACCESS_ID, APP_USER_ID, INV_ORG_ID, ACCESS_LEVEL)
VALUES (1000003, 1000002, 1000001, 'CASHIER_ONLY');

-- 7. CATEGORIES (شجرة المجموعات)
INSERT INTO POS_ITEM_CATEGORIES (CATEGORY_ID, CATEGORY_CODE, CATEGORY_NAME_AR, CATEGORY_NAME_EN, SORT_ORDER, IS_ACTIVE)
VALUES (1000001, 'CAT_BEVERAGES', 'مشروبات ومأكولات', 'Beverages & Snacks', 1, 'Y');

INSERT INTO POS_ITEM_CATEGORIES (CATEGORY_ID, CATEGORY_CODE, CATEGORY_NAME_AR, CATEGORY_NAME_EN, SORT_ORDER, IS_ACTIVE)
VALUES (1000002, 'CAT_APPAREL', 'ملابس وأزياء', 'Apparel & Fashion', 2, 'Y');

INSERT INTO POS_ITEM_CATEGORIES (CATEGORY_ID, CATEGORY_CODE, CATEGORY_NAME_AR, CATEGORY_NAME_EN, SORT_ORDER, IS_ACTIVE)
VALUES (1000003, 'CAT_ELECTRONICS', 'إلكترونيات واكسسوارات', 'Electronics & Accessories', 3, 'Y');

-- 8. ITEMS (الأصناف)
-- Item 1: Specialty Coffee (F&B / Retail)
INSERT INTO POS_ITEMS (
    ITEM_ID, ITEM_CODE, ITEM_NAME_AR, ITEM_NAME_EN, CATEGORY_ID,
    ITEM_TYPE, SECTOR_TYPE, PRIMARY_UOM_CODE, BARCODE, HAS_VARIANTS,
    IS_TAXABLE, COST_PRICE, MIN_SALE_PRICE, IS_ACTIVE
) VALUES (
    1000001, 'ITM_COFFEE_LATTE', 'كافيه لاتيه كلاسيك', 'Classic Cafe Latte', 1000001,
    'PRODUCT', 'FNB', 'EA', '628100000001', 'N',
    'Y', 4.50, 12.00, 'Y'
);

-- Item 2: Polo Shirt (Matrix Variants: Size/Color)
INSERT INTO POS_ITEMS (
    ITEM_ID, ITEM_CODE, ITEM_NAME_AR, ITEM_NAME_EN, CATEGORY_ID,
    ITEM_TYPE, SECTOR_TYPE, PRIMARY_UOM_CODE, BARCODE, HAS_VARIANTS,
    IS_TAXABLE, COST_PRICE, MIN_SALE_PRICE, IS_ACTIVE
) VALUES (
    1000002, 'ITM_POLO_SHIRT', 'قميص بولو قطني كلاسيك', 'Classic Cotton Polo Shirt', 1000002,
    'PRODUCT', 'RETAIL', 'EA', '628100000002', 'Y',
    'Y', 35.00, 75.00, 'Y'
);

-- Item 3: Wireless Bluetooth Earbuds (Electronics / Serial Tracking)
INSERT INTO POS_ITEMS (
    ITEM_ID, ITEM_CODE, ITEM_NAME_AR, ITEM_NAME_EN, CATEGORY_ID,
    ITEM_TYPE, SECTOR_TYPE, PRIMARY_UOM_CODE, BARCODE, HAS_VARIANTS,
    HAS_SERIAL, IS_TAXABLE, COST_PRICE, MIN_SALE_PRICE, IS_ACTIVE
) VALUES (
    1000003, 'ITM_BT_EARBUDS_PRO', 'سماعات لاسلكية برو', 'Wireless Earbuds Pro', 1000003,
    'PRODUCT', 'RETAIL', 'EA', '628100000003', 'N',
    'Y', 120.00, 249.00, 'Y'
);

-- 9. ITEM VARIANTS (متغيرات الأصناف)
INSERT INTO POS_ITEM_VARIANTS (
    VARIANT_ID, ITEM_ID, SKU_CODE, VARIANT_NAME_EN, BARCODE, COST_PRICE, IS_ACTIVE
) VALUES (
    1000001, 1000002, 'POLO-BLK-M', 'Polo Shirt - Black Medium', '628100000201', 35.00, 'Y'
);

INSERT INTO POS_ITEM_VARIANTS (
    VARIANT_ID, ITEM_ID, SKU_CODE, VARIANT_NAME_EN, BARCODE, COST_PRICE, IS_ACTIVE
) VALUES (
    1000002, 1000002, 'POLO-BLK-L', 'Polo Shirt - Black Large', '628100000202', 35.00, 'Y'
);

INSERT INTO POS_ITEM_VARIANTS (
    VARIANT_ID, ITEM_ID, SKU_CODE, VARIANT_NAME_EN, BARCODE, COST_PRICE, IS_ACTIVE
) VALUES (
    1000003, 1000002, 'POLO-WHT-M', 'Polo Shirt - White Medium', '628100000203', 35.00, 'Y'
);

-- ITEM ORG ASSIGNMENT
INSERT INTO POS_ITEM_ORG_ASSIGN (ASSIGNMENT_ID, ITEM_ID, INV_ORG_ID, IS_SELLABLE, IS_PURCHASABLE, IS_STOCKABLE)
VALUES (1000001, 1000001, 1000001, 'Y', 'Y', 'Y');
INSERT INTO POS_ITEM_ORG_ASSIGN (ASSIGNMENT_ID, ITEM_ID, INV_ORG_ID, IS_SELLABLE, IS_PURCHASABLE, IS_STOCKABLE)
VALUES (1000002, 1000002, 1000001, 'Y', 'Y', 'Y');
INSERT INTO POS_ITEM_ORG_ASSIGN (ASSIGNMENT_ID, ITEM_ID, INV_ORG_ID, IS_SELLABLE, IS_PURCHASABLE, IS_STOCKABLE)
VALUES (1000003, 1000003, 1000001, 'Y', 'Y', 'Y');

-- 10. PRICE LISTS (قوائم الأسعار)
INSERT INTO POS_PRICE_LISTS (
    PRICE_LIST_ID, PRICE_LIST_CODE, PRICE_LIST_NAME, PRICE_LIST_TYPE,
    CURRENCY_CODE, IS_ACTIVE
) VALUES (
    1000001, 'STANDARD_RETAIL_SAR', 'Standard Retail Price List SAR', 'STANDARD',
    'SAR', 'Y'
);

INSERT INTO POS_PRICE_LIST_LINES (
    PRICE_LINE_ID, PRICE_LIST_ID, ITEM_ID, VARIANT_ID, UOM_CODE, LIST_PRICE, MIN_PRICE, IS_ACTIVE
) VALUES (
    1000001, 1000001, 1000001, NULL, 'EA', 16.00, 12.00, 'Y'
);

INSERT INTO POS_PRICE_LIST_LINES (
    PRICE_LINE_ID, PRICE_LIST_ID, ITEM_ID, VARIANT_ID, UOM_CODE, LIST_PRICE, MIN_PRICE, IS_ACTIVE
) VALUES (
    1000002, 1000001, 1000002, 1000001, 'EA', 89.00, 75.00, 'Y'
);

INSERT INTO POS_PRICE_LIST_LINES (
    PRICE_LINE_ID, PRICE_LIST_ID, ITEM_ID, VARIANT_ID, UOM_CODE, LIST_PRICE, MIN_PRICE, IS_ACTIVE
) VALUES (
    1000003, 1000001, 1000002, 1000002, 'EA', 89.00, 75.00, 'Y'
);

INSERT INTO POS_PRICE_LIST_LINES (
    PRICE_LINE_ID, PRICE_LIST_ID, ITEM_ID, VARIANT_ID, UOM_CODE, LIST_PRICE, MIN_PRICE, IS_ACTIVE
) VALUES (
    1000004, 1000001, 1000002, 1000003, 'EA', 89.00, 75.00, 'Y'
);

INSERT INTO POS_PRICE_LIST_LINES (
    PRICE_LINE_ID, PRICE_LIST_ID, ITEM_ID, VARIANT_ID, UOM_CODE, LIST_PRICE, MIN_PRICE, IS_ACTIVE
) VALUES (
    1000005, 1000001, 1000003, NULL, 'EA', 299.00, 249.00, 'Y'
);

-- 11. PAYMENT METHODS (طرق الدفع)
INSERT INTO POS_PAYMENT_METHODS (
    PAYMENT_METHOD_ID, METHOD_CODE, METHOD_NAME_EN, METHOD_NAME_AR,
    METHOD_TYPE, IS_CHANGE_APPLICABLE, SORT_ORDER, IS_ACTIVE
) VALUES (
    1000001, 'CASH', 'Cash (SAR)', 'نقدي (ريال)', 'CASH', 'Y', 1, 'Y'
);

INSERT INTO POS_PAYMENT_METHODS (
    PAYMENT_METHOD_ID, METHOD_CODE, METHOD_NAME_EN, METHOD_NAME_AR,
    METHOD_TYPE, IS_CHANGE_APPLICABLE, SORT_ORDER, IS_ACTIVE
) VALUES (
    1000002, 'MADA', 'Mada Debit Card', 'بطاقة مدى', 'CARD', 'N', 2, 'Y'
);

INSERT INTO POS_PAYMENT_METHODS (
    PAYMENT_METHOD_ID, METHOD_CODE, METHOD_NAME_EN, METHOD_NAME_AR,
    METHOD_TYPE, IS_CHANGE_APPLICABLE, SORT_ORDER, IS_ACTIVE
) VALUES (
    1000003, 'VISA_MC', 'Credit Card (Visa/Mastercard)', 'بطاقة ائتمان', 'CARD', 'N', 3, 'Y'
);

INSERT INTO POS_PAYMENT_METHODS (
    PAYMENT_METHOD_ID, METHOD_CODE, METHOD_NAME_EN, METHOD_NAME_AR,
    METHOD_TYPE, IS_CHANGE_APPLICABLE, SORT_ORDER, IS_ACTIVE
) VALUES (
    1000004, 'APPLE_PAY', 'Apple Pay / Contactless', 'أبل باي / دفع لا تلامسي', 'CARD', 'N', 4, 'Y'
);

-- 12. TAX SETUP (VAT 15% - السعودية)
INSERT INTO POS_TAX_REGIMES (REGIME_ID, REGIME_CODE, REGIME_NAME, COUNTRY_CODE, IS_ACTIVE)
VALUES (1000001, 'VAT_SA', 'Saudi Arabia Value Added Tax', 'SA', 'Y');

INSERT INTO POS_TAX_TYPES (TAX_TYPE_ID, REGIME_ID, TAX_CODE, TAX_NAME_EN, TAX_NAME_AR, TAX_CLASS, IS_ACTIVE)
VALUES (1000001, 1000001, 'VAT_STD', 'Standard VAT', 'ضريبة القيمة المضافة القياسية', 'VAT', 'Y');

INSERT INTO POS_TAX_RATES (TAX_RATE_ID, TAX_TYPE_ID, RATE_CODE, RATE_PERCENT, EFFECTIVE_FROM, IS_ACTIVE)
VALUES (1000001, 1000001, 'VAT_15', 15.0000, TO_DATE('2020-07-01','YYYY-MM-DD'), 'Y');

INSERT INTO POS_TAX_RULES (RULE_ID, TAX_RATE_ID, RULE_NAME, PRIORITY, LEGAL_ENTITY_ID, IS_ACTIVE)
VALUES (1000001, 1000001, 'Default Standard 15% VAT Rule', 100, 1000001, 'Y');

-- 13. CHART OF ACCOUNTS & FINANCIALS (شجرة الحسابات الأساسية)
INSERT INTO POS_COA_ACCOUNTS (ACCOUNT_ID, ACCOUNT_CODE, ACCOUNT_NAME_EN, ACCOUNT_NAME_AR, ACCOUNT_TYPE, NORMAL_BALANCE, LEGAL_ENTITY_ID, IS_ACTIVE)
VALUES (1000001, '01-100-1010-00', 'Cash on Hand (POS Cashier)', 'نقدية الصندوق (نقطة البيع)', 'ASSET', 'DEBIT', 1000001, 'Y');

INSERT INTO POS_COA_ACCOUNTS (ACCOUNT_ID, ACCOUNT_CODE, ACCOUNT_NAME_EN, ACCOUNT_NAME_AR, ACCOUNT_TYPE, NORMAL_BALANCE, LEGAL_ENTITY_ID, IS_ACTIVE)
VALUES (1000002, '01-100-1020-00', 'Bank Settlement Account (Mada/Visa)', 'حساب تسوية بطاقات مدى وفيزا', 'ASSET', 'DEBIT', 1000001, 'Y');

INSERT INTO POS_COA_ACCOUNTS (ACCOUNT_ID, ACCOUNT_CODE, ACCOUNT_NAME_EN, ACCOUNT_NAME_AR, ACCOUNT_TYPE, NORMAL_BALANCE, LEGAL_ENTITY_ID, IS_ACTIVE)
VALUES (1000003, '01-100-1200-00', 'Accounts Receivable (Trade Debtors)', 'حسابات المدينين والعملاء الآجل', 'ASSET', 'DEBIT', 1000001, 'Y');

INSERT INTO POS_COA_ACCOUNTS (ACCOUNT_ID, ACCOUNT_CODE, ACCOUNT_NAME_EN, ACCOUNT_NAME_AR, ACCOUNT_TYPE, NORMAL_BALANCE, LEGAL_ENTITY_ID, IS_ACTIVE)
VALUES (1000004, '01-100-1400-00', 'Merchandise Inventory Asset', 'مخزون بضاعة البيع بالمخازن', 'ASSET', 'DEBIT', 1000001, 'Y');

INSERT INTO POS_COA_ACCOUNTS (ACCOUNT_ID, ACCOUNT_CODE, ACCOUNT_NAME_EN, ACCOUNT_NAME_AR, ACCOUNT_TYPE, NORMAL_BALANCE, LEGAL_ENTITY_ID, IS_ACTIVE)
VALUES (1000005, '01-100-2200-00', 'VAT Output Tax Payable', 'أمانات ضريبة القيمة المضافة المستحقة', 'LIABILITY', 'CREDIT', 1000001, 'Y');

INSERT INTO POS_COA_ACCOUNTS (ACCOUNT_ID, ACCOUNT_CODE, ACCOUNT_NAME_EN, ACCOUNT_NAME_AR, ACCOUNT_TYPE, NORMAL_BALANCE, LEGAL_ENTITY_ID, IS_ACTIVE)
VALUES (1000006, '01-100-4100-00', 'Retail Sales Revenue', 'إيرادات مبيعات التجزئة', 'REVENUE', 'CREDIT', 1000001, 'Y');

INSERT INTO POS_COA_ACCOUNTS (ACCOUNT_ID, ACCOUNT_CODE, ACCOUNT_NAME_EN, ACCOUNT_NAME_AR, ACCOUNT_TYPE, NORMAL_BALANCE, LEGAL_ENTITY_ID, IS_ACTIVE)
VALUES (1000007, '01-100-4200-00', 'Sales Discounts & Promotions', 'خصومات ومسموحات المبيعات', 'CONTRA', 'DEBIT', 1000001, 'Y');

INSERT INTO POS_COA_ACCOUNTS (ACCOUNT_ID, ACCOUNT_CODE, ACCOUNT_NAME_EN, ACCOUNT_NAME_AR, ACCOUNT_TYPE, NORMAL_BALANCE, LEGAL_ENTITY_ID, IS_ACTIVE)
VALUES (1000008, '01-100-5100-00', 'Cost of Goods Sold (COGS)', 'تكلفة البضاعة المباعة', 'EXPENSE', 'DEBIT', 1000001, 'Y');

INSERT INTO POS_COA_ACCOUNTS (ACCOUNT_ID, ACCOUNT_CODE, ACCOUNT_NAME_EN, ACCOUNT_NAME_AR, ACCOUNT_TYPE, NORMAL_BALANCE, LEGAL_ENTITY_ID, IS_ACTIVE)
VALUES (1000009, '01-100-5200-00', 'Cashier Over/Short Variance', 'عجز وزيادة نقدية الكاشير', 'EXPENSE', 'DEBIT', 1000001, 'Y');

-- GL OPEN PERIOD (الفترة المحاسبية الحالية)
INSERT INTO POS_GL_PERIODS (
    PERIOD_ID, LEGAL_ENTITY_ID, PERIOD_NAME, PERIOD_YEAR, PERIOD_NUM,
    START_DATE, END_DATE, CLOSE_STATUS
) VALUES (
    1000001, 1000001, '2026-08', 2026, 8,
    TO_DATE('2026-08-01','YYYY-MM-DD'), TO_DATE('2026-08-31','YYYY-MM-DD'), 'OPEN'
);

-- 14. INVENTORY OPENING BALANCES (أرصدة المخزون الافتتاحية)
INSERT INTO POS_INVENTORY_BALANCES (
    BALANCE_ID, INV_ORG_ID, SUBINV_ID, ITEM_ID, VARIANT_ID, UOM_CODE,
    QUANTITY_ON_HAND, TOTAL_COST, LAST_TRANSACTION_DATE
) VALUES (
    1000001, 1000001, 1000001, 1000001, NULL, 'EA',
    500.000000, 2250.000000, SYSDATE
);

INSERT INTO POS_INVENTORY_BALANCES (
    BALANCE_ID, INV_ORG_ID, SUBINV_ID, ITEM_ID, VARIANT_ID, UOM_CODE,
    QUANTITY_ON_HAND, TOTAL_COST, LAST_TRANSACTION_DATE
) VALUES (
    1000002, 1000001, 1000001, 1000002, 1000001, 'EA',
    100.000000, 3500.000000, SYSDATE
);

INSERT INTO POS_INVENTORY_BALANCES (
    BALANCE_ID, INV_ORG_ID, SUBINV_ID, ITEM_ID, VARIANT_ID, UOM_CODE,
    QUANTITY_ON_HAND, TOTAL_COST, LAST_TRANSACTION_DATE
) VALUES (
    1000003, 1000001, 1000001, 1000003, NULL, 'EA',
    40.000000, 4800.000000, SYSDATE
);

-- FIFO INITIAL COST LAYERS
INSERT INTO POS_FIFO_COST_LAYERS (
    LAYER_ID, INV_ORG_ID, SUBINV_ID, ITEM_ID, VARIANT_ID,
    RECEIPT_DATE, ORIGINAL_QUANTITY, REMAINING_QUANTITY, UNIT_COST, LAYER_STATUS
) VALUES (
    1000001, 1000001, 1000001, 1000001, NULL,
    SYSDATE - 10, 500.000000, 500.000000, 4.500000, 'OPEN'
);

INSERT INTO POS_FIFO_COST_LAYERS (
    LAYER_ID, INV_ORG_ID, SUBINV_ID, ITEM_ID, VARIANT_ID,
    RECEIPT_DATE, ORIGINAL_QUANTITY, REMAINING_QUANTITY, UNIT_COST, LAYER_STATUS
) VALUES (
    1000002, 1000001, 1000001, 1000002, 1000001,
    SYSDATE - 5, 100.000000, 100.000000, 35.000000, 'OPEN'
);

INSERT INTO POS_FIFO_COST_LAYERS (
    LAYER_ID, INV_ORG_ID, SUBINV_ID, ITEM_ID, VARIANT_ID,
    RECEIPT_DATE, ORIGINAL_QUANTITY, REMAINING_QUANTITY, UNIT_COST, LAYER_STATUS
) VALUES (
    1000003, 1000001, 1000001, 1000003, NULL,
    SYSDATE - 3, 40.000000, 40.000000, 120.000000, 'OPEN'
);

-- 15. SAMPLE CUSTOMERS & RESTAURANT TABLES (عملاء وطاولات)
INSERT INTO POS_CUSTOMERS (
    CUSTOMER_ID, CUSTOMER_CODE, CUSTOMER_NAME_AR, CUSTOMER_NAME_EN,
    CUSTOMER_TYPE, PHONE, CREDIT_LIMIT, INV_ORG_ID, IS_ACTIVE
) VALUES (
    1000001, 'CUST_WALKIN', 'عميل نقدي عام', 'Walk-in Cash Customer',
    'WALK_IN', '0500000000', 0, 1000001, 'Y'
);

INSERT INTO POS_CUSTOMERS (
    CUSTOMER_ID, CUSTOMER_CODE, CUSTOMER_NAME_AR, CUSTOMER_NAME_EN,
    CUSTOMER_TYPE, TAX_REGISTRATION_NO, PHONE, CREDIT_LIMIT, INV_ORG_ID, IS_ACTIVE
) VALUES (
    1000002, 'CUST_ARAMCO_EMP', 'شركة أرامكو - عملاء الشركات', 'Saudi Aramco Corporate Client',
    'COMPANY', '300000000000003', '0551234567', 50000.00, 1000001, 'Y'
);

INSERT INTO POS_TABLES (TABLE_ID, TABLE_CODE, TABLE_NAME, INV_ORG_ID, FLOOR_NO, CAPACITY, TABLE_STATUS, IS_ACTIVE)
VALUES (1000001, 'TBL_01', 'Indoor Table 1', 1000001, 1, 4, 'AVAILABLE', 'Y');

INSERT INTO POS_TABLES (TABLE_ID, TABLE_CODE, TABLE_NAME, INV_ORG_ID, FLOOR_NO, CAPACITY, TABLE_STATUS, IS_ACTIVE)
VALUES (1000002, 'TBL_02', 'Family Booth 2', 1000001, 1, 6, 'AVAILABLE', 'Y');

INSERT INTO POS_TABLES (TABLE_ID, TABLE_CODE, TABLE_NAME, INV_ORG_ID, FLOOR_NO, CAPACITY, TABLE_STATUS, IS_ACTIVE)
VALUES (1000003, 'TBL_03', 'Outdoor Terrace 3', 1000001, 2, 2, 'AVAILABLE', 'Y');

COMMIT;